Repository comfortdelgro/compass-design, pull requests merged in 2023-06, with the labels that each got.

#745 docs: revert doc calendar
  apps/docs/src/components/Calendars.tsx
  apps/docs/src/components/DatePickers.tsx
  apps/docs/src/pages/components/calendar.mdx
  apps/docs/src/pages/components/date-picker.mdx
  apps/docs/src/pages/components/date-range-picker.mdx
  apps/docs/src/pages/components/range-calendar.mdx
  packages/react-compass/src/range-calendar/range-calendar.tsx
Labels: documentation

#796 fix: accordion ui
  packages/react-compass/src/accordion/accordion-button.styles.ts
Labels: bug

#789 Bug/fix slider
  packages/react-compass/src/slider/slider.styles.ts
Labels: bug

#794 Feature/range calendar new design
  apps/docs/src/components/Calendars.tsx
  apps/docs/src/components/DatePickers.tsx
  apps/docs/src/pages/components/date-range-picker.mdx
  apps/docs/src/pages/components/range-calendar.mdx
  packages/react-compass/src/calendar/calendar-cell.tsx
  packages/react-compass/src/calendar/calendar.stories.tsx
  packages/react-compass/src/calendar/calendar.tsx
  packages/react-compass/src/calendar/hooks/useCalendarState.ts
  packages/react-compass/src/calendar/types/calendar.types.ts
  packages/react-compass/src/calendar/types/date-picker.types.ts
  packages/react-compass/src/calendar/types/date-range-picker.types.ts
  packages/react-compass/src/calendar/utils/common.ts
  packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
  packages/react-compass/src/date-range-picker/date-range-picker.tsx
  packages/react-compass/src/index.ts
  packages/react-compass/src/range-calendar/index.ts
  packages/react-compass/src/range-calendar/range-calendar-shortcuts.styles.ts
  packages/react-compass/src/range-calendar/range-calendar-shortcuts.tsx
  packages/react-compass/src/range-calendar/range-calendar.stories.tsx
  packages/react-compass/src/range-calendar/range-calendar.style.ts
  packages/react-compass/src/range-calendar/range-calendar.tsx
  packages/react-compass/src/range-calendar/useRangeCalendarShorcuts.ts
Labels: enhancement

#793 Bug/fix speed dial
  apps/docs/src/pages/components/speed-dial.mdx
  packages/react-compass/src/speed-dial/speed-dial.styles.ts
  packages/react-compass/src/speed-dial/speed-dial.tsx
Labels: bug, enhancement

#787 [yagin][fix button magin]
  packages/react-compass/src/button/button.stories.tsx
  packages/react-compass/src/button/button.styles.ts
Labels: bug

#803 [yagin][fix styles back ground for button]
  apps/docs/src/styles/global.css
Labels: bug

#795 feature: create gutter control component
  apps/docs/src/pages/components/gutter.mdx
  apps/docs/src/styles/Home.module.css
  packages/react-compass/src/gutter/gutter-content.styles.ts
  packages/react-compass/src/gutter/gutter-content.tsx
  packages/react-compass/src/gutter/gutter-context.tsx
  packages/react-compass/src/gutter/gutter-resizer.styles.tsx
  packages/react-compass/src/gutter/gutter-resizer.tsx
  packages/react-compass/src/gutter/gutter.stories.tsx
  packages/react-compass/src/gutter/gutter.styles.ts
  packages/react-compass/src/gutter/gutter.tsx
  packages/react-compass/src/gutter/index.ts
  packages/react-compass/src/gutter/useResizer.ts
  packages/react-compass/src/index.ts
Labels: enhancement

#819 Feature/table add enable row selection
  apps/docs/src/components/TableV2.tsx
  packages/react-compass/src/table-v2/react-table-checkbox-cell.tsx
  packages/react-compass/src/table-v2/react-table-checkbox.tsx
  packages/react-compass/src/table-v2/react-table.tsx
  packages/react-compass/src/table-v2/table-v2.stories.tsx
Labels: enhancement

#730 Feature/data grid
  apps/docs/src/components/DataGrid.tsx
  apps/docs/src/components/person-status.tsx
  apps/docs/src/pages/components/data-grid.mdx
  packages/react-compass/src/data-grid/data-grid-cell.styles.ts
  packages/react-compass/src/data-grid/data-grid-cell.tsx
  packages/react-compass/src/data-grid/data-grid-checkbox-cell.styles.ts
  packages/react-compass/src/data-grid/data-grid-checkbox-cell.tsx
  packages/react-compass/src/data-grid/data-grid-checkbox.styles.ts
  packages/react-compass/src/data-grid/data-grid-checkbox.tsx
  packages/react-compass/src/data-grid/data-grid-column-header-filter.styles.ts
  packages/react-compass/src/data-grid/data-grid-column-header-filter.tsx
  packages/react-compass/src/data-grid/data-grid-column-header.styles.ts
  packages/react-compass/src/data-grid/data-grid-column-header.tsx
  packages/react-compass/src/data-grid/data-grid-config-model.ts
  packages/react-compass/src/data-grid/data-grid-footer.styles.ts
  packages/react-compass/src/data-grid/data-grid-footer.tsx
  packages/react-compass/src/data-grid/data-grid-header-row.styles.ts
  packages/react-compass/src/data-grid/data-grid-header-row.tsx
  packages/react-compass/src/data-grid/data-grid-nodata.styles.ts
  packages/react-compass/src/data-grid/data-grid-nodata.tsx
  packages/react-compass/src/data-grid/data-grid-progress.styles.ts
  packages/react-compass/src/data-grid/data-grid-progress.tsx
  packages/react-compass/src/data-grid/data-grid-resizer.styles.ts
  packages/react-compass/src/data-grid/data-grid-resizer.tsx
  packages/react-compass/src/data-grid/data-grid-row-group.styles.ts
  packages/react-compass/src/data-grid/data-grid-row-group.tsx
  packages/react-compass/src/data-grid/data-grid-row.styles.ts
  packages/react-compass/src/data-grid/data-grid-row.tsx
  packages/react-compass/src/data-grid/data-grid-toolbar.styles.tsx
  packages/react-compass/src/data-grid/data-grid-toolbar.tsx
  packages/react-compass/src/data-grid/data-grid.stories.tsx
  packages/react-compass/src/data-grid/data-grid.styles.ts
  packages/react-compass/src/data-grid/data-grid.tsx
  packages/react-compass/src/data-grid/for story/person-status.tsx
  packages/react-compass/src/data-grid/index.ts
  packages/react-compass/src/data-grid/makeData.ts
  packages/react-compass/src/index.ts
Labels: documentation, enhancement

#840 [CDS-319] Add 6 inputs demo and responsive
  apps/docs/src/pages/components/otp-Input.mdx
  packages/react-compass/src/otp-input/otpInput.stories.tsx
  packages/react-compass/src/otp-input/otpInput.styles.ts
Labels: enhancement

#821 [CDS-336] Rich Text Editor more samples
  packages/react-compass/package.json
  packages/react-compass/src/rich-text-editor/rich-text-editor.stories.tsx
  packages/react-compass/src/rich-text-editor/rich-text-editor.styles.ts
  packages/react-compass/src/rich-text-editor/rich-text-editor.tsx
  pnpm-lock.yaml
Labels: documentation

#828 [CDS-335] Add Dialog responsive
  packages/react-compass/src/dialog/dialog-actions.tsx
  packages/react-compass/src/dialog/dialog.stories.tsx
  packages/react-compass/src/dialog/dialog.styles.ts
Labels: enhancement

#841 [CDS-369] Add DarkTheme for the rest components
  apps/docs/src/styles/global.css
  packages/react-compass/src/list/list.stories.tsx
  packages/react-compass/src/popover/popover.stories.tsx
  packages/react-compass/src/quantity-toggle/quantity-toggle.styles.ts
  packages/react-compass/src/searchfield/searchfield.styles.ts
  packages/react-compass/src/searchfield/searchfield.tsx
  packages/react-compass/src/table-v2/react-table-row.styles.ts
  packages/react-compass/src/table-v2/react-table.styles.ts
  packages/react-compass/src/table/table.styles.ts
  packages/react-compass/src/tabs/tab/index.styles.ts
  packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts
  packages/react-compass/src/tag-box/tag-box.styles.ts
  packages/react-compass/src/textarea/textarea.styles.ts
  packages/react-compass/src/textfield/textfield.styles.ts
  packages/react-compass/src/theme/theme.ts
  packages/react-compass/src/time-picker/time-picker.styles.ts
  packages/react-compass/src/upload-v2/upload.styles.ts
  packages/react-compass/src/upload/upload.styles.ts
Labels: bug, enhancement

#846 [CDS-358] Fix button color through out the document project
  apps/docs/src/components/BasicFooter.tsx
  apps/docs/src/components/DataGrid.tsx
  apps/docs/src/components/DatePickers.tsx
  apps/docs/src/components/Error.tsx
  apps/docs/src/components/Modal.tsx
  apps/docs/src/components/PageHeaderComponent.tsx
  apps/docs/src/components/Sidebar.tsx
  apps/docs/src/components/TableV2.tsx
  apps/docs/src/components/Toast.tsx
  apps/docs/src/pages/components/buttons.mdx
  apps/docs/src/pages/components/cards.mdx
  apps/docs/src/pages/components/dashboard-sidecard.mdx
  apps/docs/src/pages/components/date-picker.mdx
  apps/docs/src/pages/components/date-range-picker.mdx
  apps/docs/src/pages/components/navbar.mdx
  apps/docs/src/pages/components/range-calendar.mdx
  apps/docs/src/pages/components/tag-box.mdx
Labels: bug

#772 Bug/refactor tagbox
  apps/docs/src/components/TagBoxV2.tsx
  apps/docs/src/pages/components/tag-box-v2.mdx
  packages/react-compass/src/index.ts
  packages/react-compass/src/tag-box-v2/tag-box-v2.stories.tsx
  packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts
  packages/react-compass/src/tag-box-v2/tag-box-v2.tsx
Labels: documentation, enhancement

#845 [CDS-354] Fix text input box shadow
  apps/docs/src/components/Calendars.tsx
  apps/docs/src/styles/Home.module.css
Labels: bug

#843 [CDS-338] Add sidenav open delay option
  apps/docs/src/pages/components/sidenav.mdx
  packages/react-compass/src/sidenav/sidenav.stories.tsx
  packages/react-compass/src/sidenav/sidenav.tsx
Labels: enhancement

#842 [CDS-356] Fix Sidebar position
  packages/react-compass/src/sidebar/sidebar.styles.ts
Labels: bug
