Repository comfortdelgro/compass-design, pull requests merged in 2023-05, with the labels that each got.

#621 Feature/fix refactor radio
  packages/react-compass/src/radio/radio-group.tsx
  packages/react-compass/src/radio/radio.stories.tsx
  packages/react-compass/src/radio/radio.styles.ts
  packages/react-compass/src/radio/radio.tsx
Labels: enhancement

#629 Feature/fix refactor radio
  packages/react-compass/src/radio/radio-group.tsx
  packages/react-compass/src/slider/slider.tsx
Labels: bug

#649 [yagin][add error boundary for video player]
  packages/react-compass/src/video-player/video-player.tsx
Labels: bug

#652 [yagin][fix convention follow new dev branch]
  packages/react-compass/src/slider/slider.tsx
  packages/react-compass/src/speed-dial/speed-dial.styles.ts
  packages/react-compass/src/speed-dial/speed-dial.tsx
  packages/react-compass/src/video-player/video-player.tsx
Labels: bug, documentation

#663 fix: calendar null errors
  packages/react-compass/src/calendar/hooks/useCalendarState.ts
  packages/react-compass/src/calendar/hooks/useDateSegment.ts
  packages/react-compass/src/calendar/utils/common.ts
Labels: bug

#682 [yagin][remove some unnecessary console log]
  apps/docs/src/components/ColorBox.tsx
  apps/docs/src/components/TableV2.tsx
  packages/react-compass/src/carousel-v2/carousel-slider.tsx
  packages/react-compass/src/table-v2/table-v2.stories.tsx
  packages/react-compass/src/upload/upload-drag-and-drop/index.tsx
  packages/react-compass/src/video-player/volume-slider/volume-slider.tsx
Labels: bug

#696 [yagin][add onBlur for radio group]
  packages/react-compass/src/radio/radio-group.styles.ts
  packages/react-compass/src/radio/radio-group.tsx
Labels: enhancement

#703 Feature/radio add onblur
  apps/docs/src/pages/components/radio.mdx
  packages/react-compass/src/radio/radio-group.tsx
  packages/react-compass/src/radio/radio.stories.tsx
Labels: bug

#707 Fix radio
  packages/react-compass/src/radio/radio-group.tsx
  packages/react-compass/src/radio/radio.tsx
Labels: bug

#712 [yagin][replace icon compass with fontawe]
  packages/react-compass/src/alert/alert.stories.tsx
  packages/react-compass/src/avatar/avatar.stories.tsx
  packages/react-compass/src/badge/badge.stories.tsx
  packages/react-compass/src/dropdown/dropdown.stories.tsx
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx
  packages/react-compass/src/radio/radio.stories.tsx
  packages/react-compass/src/textarea/textarea.stories.tsx
  packages/react-compass/src/textfield/textfield.stories.tsx
Labels: bug

#711 fix: date picker input not working properly in react 17
  packages/react-compass/src/calendar/hooks/useDateFieldState.ts
Labels: bug

#733 fix: calendar first day of next month is not in grey color
  packages/react-compass/src/calendar/hooks/useCalendarState.ts
Labels: bug

#736 [yagin][fix some styles of tag box v2]
  packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts
  packages/react-compass/src/tag-box-v2/tag-box-v2.tsx
Labels: bug

#749 Fix/range calendar next prev month
  packages/react-compass/src/calendar/calendar-cell.style.ts
  packages/react-compass/src/calendar/calendar-cell.tsx
  packages/react-compass/src/date-picker/date-picker.stories.tsx
Labels: bug

#748 Fix/date picker reset value
  packages/react-compass/src/calendar/calendar.tsx
  packages/react-compass/src/calendar/hooks/useDateFieldState.ts
  packages/react-compass/src/range-calendar/range-calendar.tsx
Labels: bug
