Repository comfortdelgro/compass-design, pull requests merged in 2023-09, with the labels that each got.

#1070 [NGPDCP-2927] Slide action/Swiper component
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/slide-action/SlideAction.tsx
  apps/docs-v2/data/components/slide-action/SlideAction.tsx.preview
  apps/docs-v2/data/components/slide-action/SlideActionBehavior.tsx
  apps/docs-v2/data/components/slide-action/SlideActionBehavior.tsx.preview
  apps/docs-v2/data/components/slide-action/SlideActionIcon.tsx
  apps/docs-v2/data/components/slide-action/SlideActionIcon.tsx.preview
  apps/docs-v2/data/components/slide-action/SlideColorful.tsx
  apps/docs-v2/data/components/slide-action/SlideColorful.tsx.preview
  apps/docs-v2/data/components/slide-action/SlideCompact.tsx
  apps/docs-v2/data/components/slide-action/SlideCompact.tsx.preview
  apps/docs-v2/data/components/slide-action/SlideEffect.tsx
  apps/docs-v2/data/components/slide-action/SlideEffect.tsx.preview
  apps/docs-v2/data/components/slide-action/slide-action.md
  apps/docs-v2/pages/components/slide-action.tsx
  packages/react-compass/src/drawer/drawer-expander.tsx
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/index.ts
  packages/react-compass/src/slide-action/index.ts
  packages/react-compass/src/slide-action/slide-action.const.ts
  packages/react-compass/src/slide-action/slide-action.stories.tsx
  packages/react-compass/src/slide-action/slide-action.styles.ts
  packages/react-compass/src/slide-action/slide-action.tsx
  packages/react-compass/src/slide-action/slide-action.types.ts
  packages/react-compass/src/slide-action/slide-dragger.tsx
  packages/react-compass/src/utils/hooks/useDrag.tsx
Labels: documentation, h5

#1075 [NGPDCP-2926] Add example dropdown using modal and drawer
  apps/docs-v2/data/components/drawer/DrawerH5.tsx
  packages/react-compass/src/radio/radio.tsx
Labels: h5

#1073 [CDS-809] Timepicker keyboard support
  packages/react-compass/src/time-picker/time-picker-dropdown-item.tsx
  packages/react-compass/src/time-picker/time-picker-dropdown.tsx
  packages/react-compass/src/time-picker/time-picker.styles.ts
  packages/react-compass/src/time-picker/time-picker.tsx
Labels: approved

#1068 [NGPDCP-2904] Add tab component for h5
  apps/docs-v2/data/components/tabs/TabsH5.tsx
  apps/docs-v2/data/components/tabs/TabsH5.tsx.preview
  apps/docs-v2/data/components/tabs/tabs.md
  packages/react-compass/src/tabs/tab-panel/index.styles.ts
  packages/react-compass/src/tabs/tab.stories.tsx
  packages/react-compass/src/tabs/tab/index.styles.ts
  packages/react-compass/src/tabs/tabs.styles.ts
  packages/react-compass/src/tabs/utils.ts
Labels: h5

#1093 fix: multiple dropdown in docs
  apps/docs-v2/data/components/multiple-dropdown/multiple-dropdown.md
Labels: documentation

#1092 [CDS-701] Sub Banner - spacing
  packages/react-compass/src/subBanner/subBanner.styles.ts
Labels: bug, ready-for-review

#1090 [CDS-698] Banner - content spacing
  packages/react-compass/src/banner/banner.styles.ts
Labels: bug, ready-for-review

#1089 [CDS-794] Drag&Drop upload component - styling
  packages/react-compass/src/upload/upload-drag-and-drop/index.styles.ts
Labels: bug, ready-for-review

#1088 [CDS-793] Upload component - disabled styling
  packages/react-compass/src/upload/upload.styles.ts
Labels: bug, ready-for-review

#1087 [CDS-792] Upload component - font-size
  packages/react-compass/src/upload/upload.styles.ts
Labels: bug, ready-for-review

#1084 Progress bar - loading state
  apps/docs-v2/data/components/progress-bar/ProgressBarColors.tsx
  apps/docs-v2/data/components/progress-bar/ProgressBarLoading.tsx
  apps/docs-v2/data/components/progress-bar/ProgressBarLoading.tsx.preview
  apps/docs-v2/data/components/progress-bar/progress-bar.md
  packages/react-compass/src/progress-bar/progress-bar.stories.tsx
  packages/react-compass/src/progress-bar/progress-bar.styles.ts
  packages/react-compass/src/progress-bar/progress-bar.tsx
Labels: documentation

#1085 [CDS-715] Pagination skipping foward button not matching the design
  packages/react-compass/src/pagination/pagination.styles.ts
  packages/react-compass/src/pagination/pagination.tsx
Labels: bug, documentation

#1083 [NGPDCP-2920] Add modal for h5
  apps/docs-v2/data/components/modal/ModalH5.tsx
  apps/docs-v2/data/components/modal/ModalH5.tsx.preview
  apps/docs-v2/data/components/modal/modal.md
  packages/react-compass/src/modal/modal-description.tsx
  packages/react-compass/src/modal/modal-title.tsx
  packages/react-compass/src/modal/modal.stories.tsx
  packages/react-compass/src/modal/modal.styles.ts
  packages/react-compass/src/modal/modal.tsx
Labels: documentation, h5

#1071 [CDS-697] Fix for actionbar gap
  packages/react-compass/src/action-bar/ActionBar.styles.ts
Labels: ready-for-review

#1067 [CDS-699] Link - Consider styles of link with Figma
  packages/react-compass/src/link/link.stories.tsx
  packages/react-compass/src/link/link.styles.ts
Labels: need-changes

#1077 [CDS-711]Button - There's no square icon button
  apps/docs-v2/data/components/button/button.md
  apps/docs/src/pages/components/buttons.mdx
  packages/react-compass/src/button/button.stories.tsx
  packages/react-compass/src/button/button.styles.ts
  packages/react-compass/src/button/button.tsx
Labels: enhancement

#1095 [CDS-729] Carousel updates size when user resize window
  packages/react-compass/src/carousel/carousel-slider.tsx
Labels: ready-for-review

#1094 [NGPDCP-2924] Multiple choices slider h5
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/multiple-choices-slider/MultipleChoicesSlider.tsx
  apps/docs-v2/data/components/multiple-choices-slider/MultipleChoicesSlider.tsx.preview
  apps/docs-v2/data/components/multiple-choices-slider/multiple-choices-slider.md
  apps/docs-v2/pages/components/rating-slider.tsx
  packages/react-compass/src/index.ts
  packages/react-compass/src/multiple-choices-slider/index.ts
  packages/react-compass/src/multiple-choices-slider/multiple-choices-slider-item.tsx
  packages/react-compass/src/multiple-choices-slider/multiple-choices-slider.stories.tsx
  packages/react-compass/src/multiple-choices-slider/multiple-choices-slider.styles.ts
  packages/react-compass/src/multiple-choices-slider/multiple-choices-slider.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
Labels: h5

#1128 docs: Drawer - add non-modal examples
  apps/docs/data/components/drawer/DrawerCustomize.tsx
  apps/docs/data/components/drawer/DrawerH5.tsx
  apps/docs/data/components/drawer/DrawerMode.tsx
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.styles.ts
Labels: documentation, h5

#1131 [CDS-829] Fix some bug in docs
  apps/docs/components/common/Demo.tsx
  apps/docs/components/common/EditPage.tsx
  apps/docs/components/common/MarkdownElement.tsx
  apps/docs/components/layouts/AppSearch.tsx
  apps/docs/data/components/banner/BannerBasic.tsx
  apps/docs/data/components/banner/BannerCustom.tsx
  apps/docs/data/components/banner/BannerSizing.tsx
  apps/docs/data/customization/theming/theming.md
  apps/docs/data/customization/z-index/z-index.md
  apps/docs/pages/_document.tsx
  apps/docs/pages/compass-design.tsx
  packages/markdown/index.d.ts
  packages/markdown/parseMarkdown.js
  packages/markdown/prism.d.ts
Labels: documentation, ready-for-review

#1130 [CDS-811] Sub header - add actions example
  packages/react-compass/src/sub-header/sub-header.stories.tsx
Labels: documentation, ready-for-review

#1129 [CDS-834][docs-v2 improvement]
  apps/docs/data/components/avatars/GroupAvatars.tsx
  apps/docs/data/components/avatars/GroupAvatars.tsx.preview
  apps/docs/data/components/avatars/avatars.md
  apps/docs/data/components/icon/icon.md
  apps/docs/pages/foundation/overview.tsx
Labels: documentation

#1124 [CDS-816] Skeleton Not support dark theme
  apps/docs/data/components/skeleton/SkeletonAnimations.tsx
  apps/docs/data/components/skeleton/SkeletonVariants.tsx
Labels: documentation

#1123 [CDS-712] Button - add disabled state examples
  packages/react-compass/src/button/button.stories.tsx
Labels: documentation, ready-for-review

#1102 [CDS-747] improve image viewer
  apps/docs/data/components/image-viewer/ImageViewer.tsx
  apps/docs/data/components/image-viewer/ImageViewer.tsx.preview
  packages/react-compass/src/image-viewer/ViewerNav.tsx
  packages/react-compass/src/image-viewer/ViewerToolbar.tsx
  packages/react-compass/src/image-viewer/image-viewer.stories.tsx
  packages/react-compass/src/image-viewer/image-viewer.styles.ts
  packages/react-compass/src/image-viewer/types.ts
Labels: ready-for-review

#1134 [CDS-845] Sidebar items in docs should be placed in alphabetic order
  apps/docs/constants/routes.ts
  apps/docs/contexts/SideNav.ts
  apps/docs/data/components/calendar/Validation.tsx
  apps/docs/data/components/calendar/Validation.tsx.preview
  apps/docs/data/components/calendar/calendar.md
  apps/docs/data/components/checkbox/CheckboxUncontrolled.tsx
  apps/docs/data/components/checkbox/CheckboxVariant.tsx
  apps/docs/data/components/dropdown/UnControlled.tsx
  apps/docs/data/components/dropdown/UnControlled.tsx.preview
  apps/docs/data/components/dropdown/dropdown.md
  apps/docs/data/components/error/ErrorCss.tsx
  apps/docs/data/components/error/ErrorCss.tsx.preview
  apps/docs/data/components/error/error.md
  apps/docs/data/components/rating/IconRating.tsx
  apps/docs/data/components/rating/IconRating.tsx.preview
  apps/docs/data/components/rating/rating.md
  apps/docs/data/components/rich-text-editor/rich-text-editor.md
  apps/docs/data/components/sidenav/SidenavDivider.tsx
  apps/docs/data/components/sidenav/SidenavDivider.tsx.preview
  apps/docs/data/components/sidenav/SidenavItem.tsx
  apps/docs/data/components/sidenav/SidenavItem.tsx.preview
  apps/docs/data/components/sidenav/SidenavMenu.tsx
  apps/docs/data/components/sidenav/SidenavMenu.tsx.preivew
  apps/docs/data/components/sidenav/sidenav.md
  apps/docs/data/components/speed-dial/SpeedDialPosition.tsx
  apps/docs/data/components/speed-dial/SpeedDialPosition.tsx.preview
  apps/docs/data/components/speed-dial/speed-dial.md
  apps/docs/data/components/tabs/TabsBasic.tsx
  apps/docs/data/components/tabs/TabsServerInteraction.tsx
  apps/docs/data/components/tabs/TabsVariants.tsx
  apps/docs/data/components/tag-box/TagBoxBasic.tsx
  apps/docs/data/components/tag-box/tag-box.md
  apps/docs/data/components/textfield/Textfield.tsx
  apps/docs/data/components/timeline/TimelineCustom.tsx
  apps/docs/data/components/timeline/TimelineDefault.tsx
Labels: documentation

#1139 [CDS-851] NavSideApp scroll not cover all items
  apps/docs/components/layouts/DocsAppSideNav.tsx
Labels: bug, documentation

#1147 Add custom display to dropdown
  apps/docs/data/components/dropdown/DropdownControlled.tsx
  apps/docs/data/components/dropdown/DropdownControlled.tsx.preview
  apps/docs/data/components/dropdown/dropdown.md
  packages/react-compass/src/dropdown/dropdown-item.tsx
  packages/react-compass/src/dropdown/dropdown.stories.tsx
  packages/react-compass/src/dropdown/dropdown.tsx
  packages/react-compass/src/dropdown/utils.tsx
Labels: approved

#1155 [CDS-774] Error - Incorrect color/background color in Error component
  packages/react-compass/src/error/error.styles.ts
Labels: bug

#1140 fix: CDS-732, CDS-771, CDS-743, CDS-791
  packages/react-compass/src/quantity-toggle/quantity-toggle.styles.ts
  packages/react-compass/src/tag-box/tag-box.styles.ts
  packages/react-compass/src/toggle/toggle.styles.ts
  packages/react-compass/src/video-player/icon.tsx
  packages/react-compass/src/wizard/wizard.tsx
Labels: approved

#1141 [CDS-705] Update styles of Dropdown
  packages/react-compass/src/dropdown/dropdown-item.tsx
  packages/react-compass/src/dropdown/dropdown.styles.ts
Labels: approved

#1142 [CDS-772] border with text field
  packages/react-compass/src/textfield/textfield.styles.ts
Labels: approved

#1144 [CDS-726] Update styles of multiple-dropdown
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.styles.ts
Labels: approved

#1146 [CDS-781] [CDS-784]Add accessibility and fix bug large content for Chip
  packages/react-compass/src/chip/chip.stories.tsx
  packages/react-compass/src/chip/chip.styles.tsx
  packages/react-compass/src/chip/chip.tsx
Labels: approved

#1143 [CDS-777] Update border width of textarea
  packages/react-compass/src/carousel/readme.md
  packages/react-compass/src/chip/chip.stories.tsx
  packages/react-compass/src/chip/chip.styles.tsx
  packages/react-compass/src/chip/chip.tsx
  packages/react-compass/src/dropdown/dropdown-item.tsx
  packages/react-compass/src/dropdown/dropdown.styles.ts
  packages/react-compass/src/gutter/readme.md
  packages/react-compass/src/otp-input/readme.md
  packages/react-compass/src/textarea/textarea.styles.ts
  packages/react-compass/src/toast/README.md
Labels: approved

#1157 [CDS-854][Docs] Pudo component
  apps/docs/components/common/MarkdownElement.tsx
  apps/docs/constants/routes.ts
  apps/docs/data/components/drawer/drawer.md
  apps/docs/data/components/progress-bar/progress-bar.md
  apps/docs/data/components/pudo/Pudo.tsx
  apps/docs/data/components/pudo/Pudo.tsx.preview
  apps/docs/data/components/pudo/PudoCompact.tsx
  apps/docs/data/components/pudo/PudoCompact.tsx.preview
  apps/docs/data/components/pudo/PudoH5Example.tsx
  apps/docs/data/components/pudo/PudoH5Example.tsx.preview
  apps/docs/data/components/pudo/PudoLabelView.tsx
  apps/docs/data/components/pudo/PudoLabelView.tsx.preview
  apps/docs/data/components/pudo/PudoManipulation.tsx
  apps/docs/data/components/pudo/PudoManipulation.tsx.preview
  apps/docs/data/components/pudo/pudo.md
  apps/docs/data/components/slide-action/slide-action.md
  apps/docs/pages/components/pudo.tsx
  packages/react-compass/src/multiple-choices-slider/multiple-choices-slider.stories.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
  packages/react-compass/src/pudo/pudo.styles.ts
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
  packages/react-compass/src/slide-action/slide-action.stories.tsx
  packages/react-compass/src/slide-action/slide-action.styles.ts
  packages/react-compass/src/slide-action/slide-dragger.tsx
  packages/react-compass/src/utils/hooks/index.ts
  packages/react-compass/src/utils/hooks/useDeepCompareEffect.tsx
Labels: documentation, ready-for-review, h5

#1162 [NGPDCP-3058] Enhance appnav and create docs
  apps/docs/constants/routes.ts
  apps/docs/data/components/app-navigation/AppNav.tsx
  apps/docs/data/components/app-navigation/AppNav.tsx.preview
  apps/docs/data/components/app-navigation/app-navigation.md
  apps/docs/pages/components/app-navigation.tsx
  packages/react-compass/src/appnav/appnav-section.tsx
  packages/react-compass/src/appnav/appnav.stories.tsx
  packages/react-compass/src/appnav/appnav.styles.ts
  packages/react-compass/src/appnav/appnav.tsx
  packages/react-compass/src/button/button.styles.ts
  packages/react-compass/src/button/ripple.tsx
Labels: approved, h5

#1174 [NGPDCP-2901] OTP Input - add mobile UI for H5
  apps/docs/data/components/otp-input/OTPInput.tsx
  apps/docs/data/components/otp-input/OTPInput.tsx.preview
  apps/docs/data/components/otp-input/OTPInputMobile.tsx
  apps/docs/data/components/otp-input/OTPInputMobile.tsx.preview
  apps/docs/data/components/otp-input/otp-input.md
  packages/react-compass/src/otp-input/OTPInput.tsx
  packages/react-compass/src/otp-input/otpInput.stories.tsx
  packages/react-compass/src/otp-input/otpInput.styles.ts
Labels: documentation, h5

#1176 PUDO label view - long text on mobile
  packages/react-compass/src/pudo/pudo.styles.ts
Labels: h5

#1117 [CDS-717] Pagination missing "Item counting" component
  apps/docs/data/components/pagination/PaginationBasic.tsx.preview
  apps/docs/data/components/pagination/PaginationControlled.tsx.preview
  apps/docs/data/components/pagination/PaginationItemsCounting.tsx
  apps/docs/data/components/pagination/PaginationItemsCounting.tsx.preview
  apps/docs/data/components/pagination/pagination.md
  packages/react-compass/src/pagination/pagination.stories.tsx
  packages/react-compass/src/pagination/pagination.styles.ts
  packages/react-compass/src/pagination/pagination.tsx
Labels: bug, documentation, enhancement

#1154 [CDS-817][CDS-819] Rich text editor - update dropdown selected key and fix link control
  packages/react-compass/src/rich-text-editor/controls/DropdownControls/HeadingsControl.tsx
  packages/react-compass/src/rich-text-editor/controls/DropdownControls/TextAlignmentSelectorControl.tsx
  packages/react-compass/src/rich-text-editor/controls/ImageControl/ImageControl.tsx
  packages/react-compass/src/rich-text-editor/controls/LinkControl/LinkControl.tsx
  packages/react-compass/src/rich-text-editor/rich-text-editor.context.ts
  packages/react-compass/src/rich-text-editor/rich-text-editor.tsx
Labels: approved

#1181 [CDS-846] Improve docs
  apps/docs/components/common/CodeCopyButton.tsx
  apps/docs/components/common/Demo.tsx
  apps/docs/components/common/DemoToolbar.tsx
  apps/docs/components/common/MarkdownElement.tsx
  apps/docs/components/layouts/AppHeader.tsx
  apps/docs/components/layouts/AppNavbarMobile.tsx
  apps/docs/components/layouts/AppSearch.tsx
  apps/docs/components/layouts/DocsAppFrame.tsx
  apps/docs/constants/config.ts
  apps/docs/constants/index.ts
  apps/docs/pages/_app.tsx
  apps/docs/pages/global.css
Labels: documentation

#1153 [CDS-818][CDS-820] Fix styling defects and read-only mode bug in rich text editor
  packages/react-compass/src/otp-input/OTPInput.tsx
  packages/react-compass/src/rich-text-editor/controls/Control/Control.styles.ts
  packages/react-compass/src/rich-text-editor/controls/DropdownControls/ColorControl.tsx
  packages/react-compass/src/rich-text-editor/controls/DropdownControls/HeadingsControl.tsx
  packages/react-compass/src/rich-text-editor/controls/DropdownControls/TextAlignmentSelectorControl.tsx
  packages/react-compass/src/rich-text-editor/controls/ImageControl/ImageControl.tsx
  packages/react-compass/src/rich-text-editor/controls/LinkControl/LinkControl.tsx
  packages/react-compass/src/rich-text-editor/controls/controls.tsx
  packages/react-compass/src/rich-text-editor/controls/create-controls.tsx
  packages/react-compass/src/rich-text-editor/rich-text-editor.stories.tsx
  packages/react-compass/src/rich-text-editor/rich-text-editor.styles.ts
  packages/react-compass/src/rich-text-editor/toolbar/Toolbar.styles.ts
  packages/react-compass/src/rich-text-editor/toolbar/Toolbar.tsx
Labels: approved

#1193 [CDS-805] Sidenav - Style is mismatching between the component and the design
  packages/react-compass/src/sidenav/divider.tsx
  packages/react-compass/src/sidenav/sidenav-item.styles.ts
  packages/react-compass/src/sidenav/sidenav-item.tsx
  packages/react-compass/src/sidenav/sidenav.stories.tsx
  packages/react-compass/src/sidenav/sidenav.styles.ts
  packages/react-compass/src/theme/theme.ts
Labels: approved

#1192 [CDS-868] fix bug, add rich text renderer stories
  packages/react-compass/src/richtext-render/renderDocument.tsx
  packages/react-compass/src/richtext-render/richtext-renderer.stories.tsx
  packages/react-compass/src/richtext-render/richtextRender.tsx
Labels: approved

#1188 [CDS-752] react defect speed dial behavior
  apps/docs/pages/components/multiple-choices-slider.tsx
  apps/docs/pages/components/rating-slider.tsx
  packages/react-compass/src/speed-dial/speed-dial-action.tsx
  packages/react-compass/src/speed-dial/speed-dial.stories.tsx
  packages/react-compass/src/speed-dial/speed-dial.styles.ts
  packages/react-compass/src/speed-dial/speed-dial.tsx
Labels: approved

#1185 [CDS-706] [CDS-707] MenuList does not follow the Figma design
  packages/react-compass/src/menu-list/menu-list-dropdown.styles.tsx
  packages/react-compass/src/menu-list/menu-list.styles.ts
Labels: approved

#1189 [CDS-837, CDS-838, CDS-839] Table column filter feature
  packages/react-compass/src/table-v2/table-v2-column-header-filter.styles.ts
  packages/react-compass/src/table-v2/table-v2-column-header-filter.tsx
  packages/react-compass/src/table/table.stories.tsx
Labels: ready-for-review

#1180 [NGPDCP-2922] h5 textfield variants
  apps/docs/constants/routes.ts
  apps/docs/data/components/dropdown-textfield/DropdownTextfield.tsx
  apps/docs/data/components/dropdown-textfield/DropdownTextfield.tsx.preview
  apps/docs/data/components/dropdown-textfield/dropdown-textfield.md
  apps/docs/pages/components/dropdown-textfield.tsx
  packages/react-compass/src/dropdown-textfield/dropdown-textfield.stories.tsx
  packages/react-compass/src/dropdown-textfield/dropdown-textfield.styles.tsx
  packages/react-compass/src/dropdown-textfield/dropdown-textfield.tsx
  packages/react-compass/src/dropdown-textfield/index.ts
  packages/react-compass/src/dropdown/dropdown.stories.tsx
  packages/react-compass/src/dropdown/dropdown.styles.ts
  packages/react-compass/src/dropdown/dropdown.tsx
  packages/react-compass/src/index.ts
  packages/react-compass/src/textarea/textarea.stories.tsx
  packages/react-compass/src/textarea/textarea.styles.ts
  packages/react-compass/src/textfield/textfield.stories.tsx
  packages/react-compass/src/textfield/textfield.styles.ts
  packages/react-compass/src/textfield/textfield.tsx
Labels: h5

#1191 [CDS-688][fix style follow figma and logic render]
  packages/react-compass/src/alert/alert.styles.ts
  packages/react-compass/src/alert/alert.tsx
Labels: bug

#1197 [CDS-840] Table V2 - Table row - some styles mismatch with the design
  packages/react-compass/src/pagination/pagination.tsx
  packages/react-compass/src/table-v2/table-v2-cell.styles.ts
  packages/react-compass/src/table-v2/table-v2-checkbox-cell.styles.ts
  packages/react-compass/src/table-v2/table-v2-column-header.styles.ts
  packages/react-compass/src/table-v2/table-v2-column-header.tsx
  packages/react-compass/src/table-v2/table-v2-row.styles.ts
Labels: bug, enhancement

#1199 [CDS-848] Table V2 - Editable cell border styles
  packages/react-compass/src/pagination/pagination.styles.ts
  packages/react-compass/src/pagination/pagination.tsx
Labels: bug, enhancement

#1202 Fix calendar today button not disable when invalid
  packages/react-compass/src/calendar/calendar-cell.style.ts
  packages/react-compass/src/calendar/calendar.tsx
  packages/react-compass/src/date-picker/date-picker.stories.tsx
  packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
  packages/react-compass/src/range-calendar/range-calendar.tsx
Labels: bug

#1196 [CDS-865] OTP input - autofocus related issue
  packages/react-compass/src/otp-input/OTPInput.tsx
  packages/react-compass/src/otp-input/SingleInput.tsx
Labels: bug
