Repository comfortdelgro/compass-design, pull requests merged in 2023-10, with the labels that each got.

#1201 [CDS-849] Table V2 - Empty state does not match the UI desgin
  packages/react-compass/src/table-v2/editable/editable-cell.tsx
  packages/react-compass/src/table-v2/table-v2-nodata.styles.ts
  packages/react-compass/src/table-v2/table-v2-nodata.tsx
  packages/react-compass/src/table/table.stories.tsx
Labels: bug, enhancement

#1217 [CDS-900] Implementation of Spinner for static
  packages/static/src/index.ts
  packages/static/src/spinner/Spinner.stories.tsx
  packages/static/src/spinner/index.ts
  packages/static/src/spinner/spinner.tsx
  packages/static/src/spinner/styles/spinner.module.css
Labels: documentation, enhancement

#1227 [docs-v2] add more feature
  apps/docs/data/components/avatars/CustomAvatars.tsx
  apps/docs/data/components/avatars/CustomAvatars.tsx.preview
  apps/docs/data/components/avatars/IconAvatars.tsx
  apps/docs/data/components/avatars/IconAvatars.tsx.preview
  apps/docs/data/components/avatars/LetterAvatars.tsx
  apps/docs/data/components/avatars/LetterAvatars.tsx.preview
  apps/docs/data/components/avatars/SizesAvatars.tsx
  apps/docs/data/components/avatars/SizesAvatars.tsx.preview
  apps/docs/data/components/avatars/avatars.md
  apps/docs/data/components/badges/BadgeColors.tsx
  apps/docs/data/components/badges/BadgeColors.tsx.preview
  apps/docs/data/components/badges/BadgeCustomIcon.tsx
  apps/docs/data/components/badges/BadgeCustomIcon.tsx.preview
  apps/docs/data/components/badges/BadgeVariants.tsx
  apps/docs/data/components/badges/BadgeVariants.tsx.preview
  apps/docs/data/components/badges/badges.md
Labels: documentation

#1244 [CDS-927] Multiple choices slider - use static CSS
  packages/static/src/index.ts
  packages/static/src/multiple-choices-slider/index.ts
  packages/static/src/multiple-choices-slider/multiple-choices-slider-item.tsx
  packages/static/src/multiple-choices-slider/multiple-choices-slider.stories.tsx
  packages/static/src/multiple-choices-slider/multiple-choices-slider.tsx
  packages/static/src/multiple-choices-slider/styles/multiple-choices-slider.module.css
Labels: documentation

#1240 [CDS-905] Implementation of Searchfield for static
  packages/static/src/button/button.tsx
  packages/static/src/button/styles/button.module.css
  packages/static/src/index.ts
  packages/static/src/searchfield/index.ts
  packages/static/src/searchfield/searchfield.cy.tsx
  packages/static/src/searchfield/searchfield.stories.tsx
  packages/static/src/searchfield/searchfield.tsx
  packages/static/src/searchfield/styles/searchfield.module.css
Labels: enhancement

#1221 [CDS-896] Implementation of divider for static
  apps/docs/data/components/divider/DividerAlign.tsx
  apps/docs/data/components/divider/DividerBasic.tsx
  packages/static/src/divider/Divider.stories.tsx
  packages/static/src/divider/divider.tsx
  packages/static/src/divider/index.ts
  packages/static/src/divider/styles/divider.module.css
  packages/static/src/index.ts
Labels: approved

#1224 [CDS-876] [CDS-875] Convert Dropdown to static css and update logic for Chip static css
  packages/static/package.json
  packages/static/src/chip/Chip.stories.tsx
  packages/static/src/chip/chip.tsx
  packages/static/src/chip/styles/chip.module.css
  packages/static/src/dropdown/Dropdown.stories.tsx
  packages/static/src/dropdown/dropdown-context.ts
  packages/static/src/dropdown/dropdown-item.tsx
  packages/static/src/dropdown/dropdown-list.tsx
  packages/static/src/dropdown/dropdown-loading.tsx
  packages/static/src/dropdown/dropdown.combobox.tsx
  packages/static/src/dropdown/dropdown.header.tsx
  packages/static/src/dropdown/dropdown.section.tsx
  packages/static/src/dropdown/dropdown.select.tsx
  packages/static/src/dropdown/dropdown.tsx
  packages/static/src/dropdown/flags/ad.tsx
  packages/static/src/dropdown/flags/ae.tsx
  packages/static/src/dropdown/flags/af.tsx
  packages/static/src/dropdown/hooks/useInViewport.ts
  packages/static/src/dropdown/index.ts
  packages/static/src/dropdown/styles/dropdown.module.css
  packages/static/src/dropdown/utils.tsx
  packages/static/src/index.ts
  packages/static/src/popover/popover.stories.tsx
  packages/static/src/utils/pick-child.ts
  pnpm-lock.yaml
Labels: approved

#1228 [CDS-903] Implementation of Radio for static
  packages/static/src/index.ts
  packages/static/src/radio/index.ts
  packages/static/src/radio/radio-group.tsx
  packages/static/src/radio/radio.stories.tsx
  packages/static/src/radio/radio.tsx
  packages/static/src/radio/styles/radio-group.module.css
  packages/static/src/radio/styles/radio.module.css
  packages/static/src/radio/styles/tooltip.module.css
  packages/static/src/radio/tooltip.tsx
Labels: documentation, enhancement

#1273 Fix: Drawer component - not allowed to manually manipulate the body tag's inert attribute
  apps/docs/data/components/drawer/drawer.md
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/types.ts
  packages/static/src/drawer/Drawer.stories.tsx
  packages/static/src/drawer/drawer.tsx
  packages/static/src/drawer/styles/drawer-stories.module.css
  packages/static/src/drawer/types.ts
  packages/static/src/multiple-choices-slider/index.ts
  packages/static/src/multiple-choices-slider/multiple-choices-slider.tsx
Labels: bug, documentation

#1300 [CDS-926] Slider static css
  packages/static/src/drawer/drawer.tsx
  packages/static/src/drawer/styles/drawer-expander.module.css
  packages/static/src/drawer/styles/drawer.module.css
  packages/static/src/index.ts
  packages/static/src/multiple-choices-slider/multiple-choices-slider.tsx
  packages/static/src/multiple-choices-slider/styles/multiple-choices-slider.module.css
  packages/static/src/slider/index.ts
  packages/static/src/slider/slider.stories.tsx
  packages/static/src/slider/slider.tsx
  packages/static/src/slider/styles/slider-stories.module.css
  packages/static/src/slider/styles/slider.module.css
Labels: documentation, enhancement

#1305 [CDS-928] Confirm Pickup - Static CSS
  packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
  packages/static/src/confirm-pickup/confirm-pickup.stories.tsx
  packages/static/src/confirm-pickup/confirm-pickup.tsx
  packages/static/src/confirm-pickup/index.ts
  packages/static/src/confirm-pickup/styles/confirm-pickup.module.css
  packages/static/src/index.ts
Labels: documentation, enhancement

#1310 [CDS-924] Slide Action | Swiper static CSS
  packages/static/src/index.ts
  packages/static/src/slide-action/index.ts
  packages/static/src/slide-action/slide-action.const.ts
  packages/static/src/slide-action/slide-action.stories.tsx
  packages/static/src/slide-action/slide-action.tsx
  packages/static/src/slide-action/slide-action.types.ts
  packages/static/src/slide-action/slide-dragger.tsx
  packages/static/src/slide-action/styles/slide-action.module.css
  packages/static/src/slide-action/styles/stories.module.css
Labels: documentation, enhancement

#1264 [CDS-899] Implementation of pagination for static
  apps/docs/data/components/pagination/PaginationServer.tsx
  apps/docs/data/components/pagination/pagination.md
  packages/static/src/index.ts
  packages/static/src/pagination/index.ts
  packages/static/src/pagination/pagination.hooks.ts
  packages/static/src/pagination/pagination.stories.tsx
  packages/static/src/pagination/pagination.tsx
  packages/static/src/pagination/styles/pagination.module.css
Labels: enhancement

#1269 [CDS-906] Implementation of Sidebar for static
  apps/docs/data/components/sidebar/SidebarServer.tsx
  apps/docs/data/components/sidebar/sidebar.md
  packages/react-compass/src/sidebar/sidebar.styles.ts
  packages/static/src/index.ts
  packages/static/src/sidebar/index.ts
  packages/static/src/sidebar/sidebar-actions.tsx
  packages/static/src/sidebar/sidebar-content.tsx
  packages/static/src/sidebar/sidebar-title.tsx
  packages/static/src/sidebar/sidebar.stories.tsx
  packages/static/src/sidebar/sidebar.tsx
  packages/static/src/sidebar/styles/sidebar.module.css
Labels: enhancement

#1278 [CDS-936] Implementation of Sidenav for static
  packages/static/src/index.ts
  packages/static/src/sidenav/divider.tsx
  packages/static/src/sidenav/index.ts
  packages/static/src/sidenav/sidenav-context.ts
  packages/static/src/sidenav/sidenav-item.tsx
  packages/static/src/sidenav/sidenav-menu.tsx
  packages/static/src/sidenav/sidenav.stories.tsx
  packages/static/src/sidenav/sidenav.tsx
  packages/static/src/sidenav/styles/divider.module.css
  packages/static/src/sidenav/styles/sidenav-item.module.css
  packages/static/src/sidenav/styles/sidenav-menu.module.css
  packages/static/src/sidenav/styles/sidenav.module.css
Labels: enhancement

#1284 [CDS-939] Implementation of Banner for static
  apps/docs/data/components/banner/BannerServer.tsx
  apps/docs/data/components/banner/banner.md
  packages/static/src/banner/banner-description.tsx
  packages/static/src/banner/banner-image.tsx
  packages/static/src/banner/banner-title.tsx
  packages/static/src/banner/banner.stories.tsx
  packages/static/src/banner/banner.tsx
  packages/static/src/banner/index.ts
  packages/static/src/banner/styles/banner.module.css
  packages/static/src/index.ts
Labels: enhancement

#1289 [CDS-938] Implementation of Sub header for static
  packages/static/src/index.ts
  packages/static/src/sub-header/index.ts
  packages/static/src/sub-header/styles/sub-header-body.module.css
  packages/static/src/sub-header/styles/sub-header-description.module.css
  packages/static/src/sub-header/styles/sub-header-header.module.css
  packages/static/src/sub-header/styles/sub-header-image.module.css
  packages/static/src/sub-header/styles/sub-header-subtitle.module.css
  packages/static/src/sub-header/styles/sub-header-title.module.css
  packages/static/src/sub-header/styles/sub-header.module.css
  packages/static/src/sub-header/sub-header-body.tsx
  packages/static/src/sub-header/sub-header-description.tsx
  packages/static/src/sub-header/sub-header-header.tsx
  packages/static/src/sub-header/sub-header-image.tsx
  packages/static/src/sub-header/sub-header-subtitle.tsx
  packages/static/src/sub-header/sub-header-title.tsx
  packages/static/src/sub-header/sub-header.stories.tsx
  packages/static/src/sub-header/sub-header.tsx
Labels: enhancement

#1309 [CDS-965] Tabs change to static
  apps/docs/data/components/tabs/TabsServer.tsx
  apps/docs/data/components/tabs/tabServer.module.css
  apps/docs/data/components/tabs/tabs.md
  packages/static/src/index.ts
  packages/static/src/tabs/index.ts
  packages/static/src/tabs/item/index.tsx
  packages/static/src/tabs/styles/story.module.css
  packages/static/src/tabs/styles/tab-panel.module.css
  packages/static/src/tabs/styles/tab.module.css
  packages/static/src/tabs/styles/tabs.module.css
  packages/static/src/tabs/tab-panel/index.tsx
  packages/static/src/tabs/tab.stories.tsx
  packages/static/src/tabs/tab/index.tsx
  packages/static/src/tabs/tabs-paneless.tsx
  packages/static/src/tabs/tabs.tsx
  packages/static/src/tabs/utils.ts
Labels: enhancement

#1339 [hot fix] fix lockfile
  pnpm-lock.yaml
Labels: bug

#1341 [hot fix] fix docs
  apps/docs/data/components/banner/banner.md
Labels: bug
