Repository comfortdelgro/compass-design, pull requests merged in 2023-07, with the labels that each got.

#847 [CDS-397] Feat add document for image viewer
  apps/docs/src/components/ImageViewer.tsx
  apps/docs/src/pages/components/image-viewer.mdx
  apps/docs/src/pages/design/theming.mdx
  packages/react-compass/src/image-viewer/ViewerCore.tsx
  packages/react-compass/src/image-viewer/index.ts
  packages/react-compass/src/image-viewer/types.ts
  packages/react-compass/src/index.ts
Labels: documentation

#852 Rich text editor docs styling
  apps/docs/src/components/RichTextEditor.tsx
  apps/docs/src/pages/components/rich-text-editor.mdx
Labels: bug

#853 [CDS-413] Update calendar and other related documents
  apps/docs/src/components/DatePickers.tsx
  apps/docs/src/pages/_app.tsx
  apps/docs/src/pages/components/date-picker.mdx
  apps/docs/src/pages/components/date-range-picker.mdx
  packages/react-compass/src/calendar/calendar-cell.style.ts
  packages/react-compass/src/calendar/calendar.tsx
  packages/react-compass/src/calendar/components/date-field.style.ts
  packages/react-compass/src/date-picker/date-picker.stories.tsx
  packages/react-compass/src/date-picker/date-picker.tsx
  packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
Labels: documentation, enhancement

#855 [CDS-369] Verify and update for new dark theme color scheme impacts
  packages/react-compass/src/searchfield/searchfield.styles.ts
  packages/react-compass/src/searchfield/searchfield.tsx
  packages/react-compass/src/textarea/textarea.styles.ts
  packages/react-compass/src/textarea/textarea.tsx
  packages/react-compass/src/textfield/textfield.styles.ts
  packages/react-compass/src/textfield/textfield.tsx
  packages/react-compass/src/timeline/timeline.styles.ts
  packages/react-compass/src/upload-v2/upload.styles.ts
  packages/react-compass/src/upload-v2/upload.tsx
  packages/react-compass/src/upload/upload.styles.ts
  packages/react-compass/src/upload/upload.tsx
  packages/react-compass/src/video-player/video-player.styles.ts
Labels: bug

#857 [CDS-392] React compass table v 2 create architecture overview design
  packages/react-compass/src/data-grid/README.md
Labels: documentation

#849 [CDS-342] Card actions buttons responsive layout
  packages/react-compass/src/card/card-action.styles.ts
  packages/react-compass/src/card/card.styles.ts
  packages/react-compass/src/theme/breakpoints.ts
Labels: approved

#867 [CDS-391] improve popover
  packages/react-compass/src/popover/index.ts
  packages/react-compass/src/popover/popover.stories.tsx
  packages/react-compass/src/popover/popover.style.ts
  packages/react-compass/src/popover/popover.tsx
Labels: enhancement, approved

#865 [CDS-340] Improve Alert responsive layout
  packages/react-compass/src/alert/alert.styles.ts
  packages/react-compass/src/alert/alert.tsx
Labels: approved

#864 [CDS-341] Breadcrumbs responsive layout
  packages/react-compass/src/breadcrumbs/breadcrumbs.styles.ts
Labels: approved

#863 [CDS-346] Video responsive layout
  packages/react-compass/src/video-player/video-player.styles.ts
Labels: approved

#862 [CDS-418] add isReadonly and more docs usage for toggle
  apps/docs/src/pages/components/toggle.mdx
  packages/react-compass/src/toggle/toggle.stories.tsx
  packages/react-compass/src/toggle/toggle.tsx
Labels: approved

#861 Fix/docs
  apps/docs/src/components/Timeline.tsx
  apps/docs/src/components/Upload.tsx
  apps/docs/src/pages/components/box.mdx
  apps/docs/src/pages/components/grid.mdx
  apps/docs/src/pages/components/no-ssr.mdx
  apps/docs/src/pages/components/timeline.mdx
  apps/docs/src/pages/components/upload.mdx
  packages/react-compass/src/carousel-v2/carouselV2.stories.tsx
  packages/react-compass/src/carousel-v2/index.ts
  packages/react-compass/src/carousel/carousel-buttons.tsx
  packages/react-compass/src/carousel/carousel-description.tsx
  packages/react-compass/src/carousel/carousel-image-slide.tsx
  packages/react-compass/src/carousel/carousel-image.tsx
  packages/react-compass/src/carousel/carousel-mobile.tsx
  packages/react-compass/src/carousel/carousel-promotion.tsx
  packages/react-compass/src/carousel/carousel-slide.tsx
  packages/react-compass/src/carousel/carousel-slider.tsx
  packages/react-compass/src/carousel/carousel-title.tsx
  packages/react-compass/src/carousel/carousel.cy.tsx
  packages/react-compass/src/carousel/carousel.stories.tsx
  packages/react-compass/src/carousel/carousel.styles.ts
  packages/react-compass/src/carousel/carousel.tsx
  packages/react-compass/src/carousel/content-slider-dots.tsx
  packages/react-compass/src/carousel/content-slider.styles.ts
  packages/react-compass/src/carousel/content-slider.types.ts
  packages/react-compass/src/carousel/index.ts
  packages/react-compass/src/index.ts
  packages/react-compass/src/richtext-render/richtext-render.stories.tsx
  packages/react-compass/src/theme/ThemeProvider.tsx
  packages/react-compass/src/timeline/timeline.stories.tsx
  packages/react-compass/src/upload-v2/uploadV2.stories.tsx
Labels: documentation, approved

#860 [CDS-414] Error state for multiple-dropdown and its individual chip
  apps/docs/src/pages/components/multiple-dropdown.mdx
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.stories.tsx
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.styles.ts
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
  packages/react-compass/src/multiple-dropdown/option/index.styles.ts
  packages/react-compass/src/multiple-dropdown/option/index.tsx
Labels: approved

#859 [CDS-345] Radio responsive layout
  apps/docs/src/pages/components/radio.mdx
  packages/react-compass/src/radio/radio.styles.ts
  packages/react-compass/src/radio/radio.tsx
Labels: documentation, approved

#854 [CDS-401] Create document page for grid data
  apps/docs/src/components/DataGrid.tsx
  apps/docs/src/pages/components/data-grid.mdx
Labels: documentation, approved

#850 [CDS-302] Add Navbar responsive
  apps/docs/src/pages/components/navbar.mdx
  packages/react-compass/src/navbar/index.ts
  packages/react-compass/src/navbar/navbar-actions.styles.ts
  packages/react-compass/src/navbar/navbar-actions.tsx
  packages/react-compass/src/navbar/navbar-brand.styles.ts
  packages/react-compass/src/navbar/navbar-brand.tsx
  packages/react-compass/src/navbar/navbar-links.styles.ts
  packages/react-compass/src/navbar/navbar-seperator.style.ts
  packages/react-compass/src/navbar/navbar.stories.tsx
  packages/react-compass/src/navbar/navbar.styles.ts
  packages/react-compass/src/navbar/navbar.tsx
Labels: enhancement, approved

#848 [CDS-348] TableV2 - Add more sample with user interactions
  apps/docs/src/components/TableV2.tsx
  apps/docs/src/pages/components/table-v2.mdx
  packages/react-compass/src/data-grid/data-grid-cell.styles.ts
  packages/react-compass/src/data-grid/data-grid-cell.tsx
  packages/react-compass/src/data-grid/data-grid-checkbox-cell.tsx
  packages/react-compass/src/data-grid/data-grid-checkbox.tsx
  packages/react-compass/src/data-grid/data-grid-column-header-filter.styles.ts
  packages/react-compass/src/data-grid/data-grid-column-header-filter.tsx
  packages/react-compass/src/data-grid/data-grid-column-header.styles.ts
  packages/react-compass/src/data-grid/data-grid-column-header.tsx
  packages/react-compass/src/data-grid/data-grid-footer.tsx
  packages/react-compass/src/data-grid/data-grid-header-row.tsx
  packages/react-compass/src/data-grid/data-grid-nodata.styles.ts
  packages/react-compass/src/data-grid/data-grid-nodata.tsx
  packages/react-compass/src/data-grid/data-grid-progress.styles.ts
  packages/react-compass/src/data-grid/data-grid-progress.tsx
  packages/react-compass/src/data-grid/data-grid-resizer.styles.ts
  packages/react-compass/src/data-grid/data-grid-resizer.tsx
  packages/react-compass/src/data-grid/data-grid-row.styles.ts
  packages/react-compass/src/data-grid/data-grid-row.tsx
  packages/react-compass/src/data-grid/data-grid.stories.tsx
  packages/react-compass/src/data-grid/data-grid.styles.ts
  packages/react-compass/src/data-grid/data-grid.tsx
  packages/react-compass/src/data-grid/editable/editable-cell.styles.ts
  packages/react-compass/src/data-grid/editable/editable-cell.tsx
  packages/react-compass/src/data-grid/index.ts
  packages/react-compass/src/table-v2/index.ts
  packages/react-compass/src/table-v2/react-table-cell.styles.ts
  packages/react-compass/src/table-v2/react-table-cell.tsx
  packages/react-compass/src/table-v2/react-table-checkbox-cell.styles.ts
  packages/react-compass/src/table-v2/react-table-checkbox-cell.tsx
  packages/react-compass/src/table-v2/react-table-checkbox.styles.ts
  packages/react-compass/src/table-v2/react-table-checkbox.tsx
  packages/react-compass/src/table-v2/react-table-column-header.styles.ts
  packages/react-compass/src/table-v2/react-table-column-header.tsx
  packages/react-compass/src/table-v2/react-table-config-model.ts
  packages/react-compass/src/table-v2/react-table-footer.styles.ts
  packages/react-compass/src/table-v2/react-table-footer.tsx
  packages/react-compass/src/table-v2/react-table-header-row.styles.ts
  packages/react-compass/src/table-v2/react-table-header-row.tsx
  packages/react-compass/src/table-v2/react-table-nodata.styles.ts
  packages/react-compass/src/table-v2/react-table-nodata.tsx
  packages/react-compass/src/table-v2/react-table-resizer.styles.ts
  packages/react-compass/src/table-v2/react-table-resizer.tsx
  packages/react-compass/src/table-v2/react-table-row-group.styles.ts
  packages/react-compass/src/table-v2/react-table-row-group.tsx
  packages/react-compass/src/table-v2/react-table-row.styles.ts
  packages/react-compass/src/table-v2/react-table-row.tsx
  packages/react-compass/src/table-v2/react-table-toolbar.styles.tsx
  packages/react-compass/src/table-v2/react-table-toolbar.tsx
  packages/react-compass/src/table-v2/react-table.styles.ts
  packages/react-compass/src/table-v2/react-table.tsx
  packages/react-compass/src/table-v2/table-v2.stories.tsx
Labels: documentation

#851 [CDS-359] Fix menu list can not press enter or spacebar to select or expand item
  apps/docs/src/pages/components/menu-lists.mdx
  packages/react-compass/src/menu-list/menu-list-dropdown-header.styles.ts
  packages/react-compass/src/menu-list/menu-list-dropdown-header.tsx
  packages/react-compass/src/menu-list/menu-list-dropdown-item.styles.ts
  packages/react-compass/src/menu-list/menu-list-dropdown-item.tsx
  packages/react-compass/src/menu-list/menu-list-dropdown.styles.tsx
  packages/react-compass/src/menu-list/menu-list-dropdown.tsx
  packages/react-compass/src/menu-list/menu-list.styles.ts
Labels: bug, approved

#866 [CDS-423] refactor scroll item for multiple-dropdown
  packages/react-compass/src/dropdown/utils.tsx
  packages/react-compass/src/multiple-dropdown/list-box/index.tsx
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
  packages/react-compass/src/multiple-dropdown/option/index.tsx
Labels: approved

#875 fix: accordion button type
  packages/react-compass/src/accordion/accordion-button.tsx
Labels: bug

#885 [CDS-460] Add Error state for each item
  apps/docs/src/components/TagBoxV2.tsx
  apps/docs/src/pages/components/tag-box-v2.mdx
  apps/docs/src/pages/components/tag-box.mdx
  packages/react-compass/src/tag-box-v2/tag-box-v2.stories.tsx
  packages/react-compass/src/tag-box-v2/tag-box-v2.styles.ts
  packages/react-compass/src/tag-box-v2/tag-box-v2.tsx
  packages/react-compass/src/tag-box-v2/types.ts
  packages/react-compass/src/tag-box/tag-box.stories.tsx
Labels: documentation, enhancement

#886 [CDS-460] Add Error state for each item
  packages/react-compass/src/tag-box-v2/tag-box-v2.stories.tsx
Labels: enhancement

#844 [CDS-368] React Compass refactor table v2
  apps/docs/src/components/TableV2.tsx
  packages/react-compass/src/data-grid/data-grid-column-header.tsx
  packages/react-compass/src/data-grid/data-grid-row.styles.ts
  packages/react-compass/src/table-v2/table-v2.stories.tsx
Labels: enhancement

#897 [CDS-431] Add Link button
  apps/docs/src/pages/components/buttons.mdx
  packages/react-compass/src/button/button.stories.tsx
  packages/react-compass/src/button/button.styles.ts
  packages/react-compass/src/button/button.tsx
Labels: documentation, enhancement

#907 [CDS-429] Tag Box handle keyboard events
  packages/react-compass/src/tag-box/tag-box-item.tsx
  packages/react-compass/src/tag-box/tag-box.styles.ts
  packages/react-compass/src/tag-box/tag-box.tsx
Labels: enhancement, approved

#905 [CDS-427] Add accessibility to speed dial
  packages/react-compass/package.json
  packages/react-compass/src/speed-dial/speed-dial-action.tsx
  packages/react-compass/src/speed-dial/speed-dial-trigger.tsx
  packages/react-compass/src/speed-dial/speed-dial.styles.ts
  packages/react-compass/src/speed-dial/speed-dial.tsx
  packages/react-compass/src/utils/hooks/index.ts
  packages/react-compass/src/utils/hooks/useKeyboardNavigation.tsx
  packages/react-compass/src/utils/hooks/useKeyboardNavigationState.ts
  packages/react-compass/src/utils/keyboard.enum.ts
  pnpm-lock.yaml
Labels: enhancement, approved

#917 [CDS-439] Create popover docs
  packages/react-compass/src/popover/README.md
Labels: documentation

#910 [CDS-440] Rich text editor architecture design document
  packages/react-compass/src/rich-text-editor/README.md
Labels: documentation, approved

#911 Chore/add-docs-for-new-popover
  apps/docs/src/components/Popovers.tsx
  apps/docs/src/pages/components/popover.mdx
  packages/react-compass/src/popover/popover.stories.tsx
  pnpm-lock.yaml
Labels: approved

#922 [CDS-421] Accordion handle keyboard events
  packages/react-compass/src/accordion/accordion-button.tsx
  packages/react-compass/src/accordion/accordion-context.tsx
  packages/react-compass/src/accordion/accordion-title.tsx
  packages/react-compass/src/accordion/accordion.tsx
Labels: documentation, enhancement

#915 [CDS-438] Datepicker document
  packages/react-compass/src/date-picker/README.md
  packages/react-compass/src/date-range-picker/README.md
Labels: documentation

#909 [CDS-364] Feature/layout phone number
  apps/docs/src/components/LayoutInputPhoneNumber.tsx
  apps/docs/src/pages/_meta.json
  apps/docs/src/pages/layouts/InputPhoneNumber.mdx
  apps/docs/src/pages/layouts/_meta.json
  apps/docs/src/styles/layout_styles/_LayoutInputPhoneNumber.module.css
  packages/react-compass/src/upload/upload.styles.ts
Labels: documentation

#906 [CDS-333] add date range picker responsive
  apps/docs/src/pages/components/date-range-picker.mdx
  apps/docs/src/pages/components/range-calendar.mdx
  packages/react-compass/src/calendar/hooks/useSlotId.ts
  packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
  packages/react-compass/src/date-range-picker/date-range-picker.style.ts
  packages/react-compass/src/date-range-picker/date-range-picker.tsx
  packages/react-compass/src/range-calendar/range-calendar.tsx
  packages/react-compass/src/utils/use-media-query.ts
Labels: enhancement

#916 [CDS-433] Checkbox focusing state
  packages/react-compass/src/checkbox/checkbox.stories.tsx
  packages/react-compass/src/checkbox/checkbox.styles.ts
  packages/react-compass/src/checkbox/checkbox.tsx
Labels: enhancement

#904 [CDS-426] Add accessibility to file upload
  packages/react-compass/src/upload/upload.styles.ts
  packages/react-compass/src/upload/upload.tsx
Labels: enhancement, approved

#940 Prevent toggle dropdown when close to close button
  packages/react-compass/src/chip/chip.tsx
  packages/react-compass/src/multiple-dropdown/multiple-dropdown.tsx
Labels: approved

#943 [CDS-475][bug] Button content is not centered when its width is a fixed number
  packages/react-compass/src/button/button.stories.tsx
  packages/react-compass/src/button/button.styles.ts
  packages/react-compass/src/button/button.tsx
  packages/react-compass/src/timeline/timeline.styles.ts
Labels: bug

#958 [CDS-481] Typography Docs V2
  apps/docs-v2/components/common/CommonHeader.tsx
  apps/docs-v2/components/common/MarkdownDocs.tsx
  apps/docs-v2/components/common/MarkdownElement.tsx
  apps/docs-v2/components/layouts/DocsAppFrame.tsx
  apps/docs-v2/components/layouts/DocsAppToc.tsx
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/contexts/PageProps.tsx
  apps/docs-v2/data/foundation/typography/components/ExamplePanel.tsx
  apps/docs-v2/data/foundation/typography/components/FontWeightExample.tsx
  apps/docs-v2/data/foundation/typography/showcases/BodyTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/BodyTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/showcases/DisplayTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/DisplayTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/showcases/HeaderTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/HeaderTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/showcases/LabelsTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/LabelsTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/showcases/LinksTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/LinksTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/showcases/StyledTypography.tsx
  apps/docs-v2/data/foundation/typography/showcases/StyledTypography.tsx.preview
  apps/docs-v2/data/foundation/typography/typography.md
  apps/docs-v2/pages/_app.tsx
  apps/docs-v2/pages/foundation/typography.tsx
  apps/docs-v2/public/static/images/typography-background.png
  apps/docs-v2/types/common.ts
  packages/markdown/parseMarkdown.js
Labels: documentation, enhancement

#956 [CDS-466] Add overview page
  apps/docs-v2/README.md
  apps/docs-v2/components/layouts/DocsAppCustomLayout.tsx
  apps/docs-v2/pages/getting-started/overview.tsx
  apps/docs-v2/pages/global.css
  apps/docs-v2/public/static/images/overview/banner-overview.png
  apps/docs-v2/public/static/images/overview/intro-1.png
  apps/docs-v2/public/static/images/overview/intro-2.png
  apps/docs-v2/public/static/images/overview/intro-3.png
  apps/docs-v2/public/static/images/overview/intro-4.png
  apps/docs-v2/public/static/images/overview/intro-5.png
  apps/docs-v2/public/static/images/overview/intro-6.png
Labels: documentation, approved

#978 [CDS-515] Breadcrumb make app crashed when click on it
  apps/docs-v2/components/common/CommonHeader.tsx
Labels: approved

#974 [CDS-467] Feat add colors page
  apps/docs-v2/components/layouts/DocsAppCustomLayout.tsx
  apps/docs-v2/components/layouts/DocsAppFrame.tsx
  apps/docs-v2/components/layouts/DocsAppLayout.tsx
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/foundation/colors/colors.md
  apps/docs-v2/data/foundation/colors/components/ColorBox.tsx
  apps/docs-v2/data/foundation/colors/showcases/Backgrounds.tsx
  apps/docs-v2/data/foundation/colors/showcases/Backgrounds.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/DividersBorders.tsx
  apps/docs-v2/data/foundation/colors/showcases/DividersBorders.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/Gradients.tsx
  apps/docs-v2/data/foundation/colors/showcases/Gradients.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/Grays.tsx
  apps/docs-v2/data/foundation/colors/showcases/Grays.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/Overlays.tsx
  apps/docs-v2/data/foundation/colors/showcases/Overlays.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/PrimaryColors.tsx
  apps/docs-v2/data/foundation/colors/showcases/PrimaryColors.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/SecondaryColors.tsx
  apps/docs-v2/data/foundation/colors/showcases/SecondaryColors.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/TextColors.tsx
  apps/docs-v2/data/foundation/colors/showcases/TextColors.tsx.preview
  apps/docs-v2/data/foundation/colors/showcases/Theme.tsx
  apps/docs-v2/data/foundation/colors/showcases/Theme.tsx.preview
  apps/docs-v2/pages/foundation/colors.tsx
  apps/docs-v2/pages/getting-started/overview.tsx
  apps/docs-v2/public/static/images/colors-background.png
Labels: approved

#973 [CDS-498] List View scan and enhance accessibility
  packages/react-compass/src/list/drag-and-drop/index.styles.ts
  packages/react-compass/src/list/drag-and-drop/item/index.tsx
  packages/react-compass/src/list/drag-and-drop/item/outlet.tsx
  packages/react-compass/src/list/list-card.tsx
  packages/react-compass/src/list/list.stories.tsx
Labels: approved

#972 [CDS-505] feature: apply accessibility to tab
  packages/react-compass/src/tabs/tab-panel/index.tsx
  packages/react-compass/src/tabs/tab.stories.tsx
  packages/react-compass/src/tabs/tab/index.styles.ts
  packages/react-compass/src/tabs/tab/index.tsx
  packages/react-compass/src/tabs/tabs.tsx
  packages/react-compass/src/utils/hooks/useKeyboardNavigation.tsx
Labels: enhancement, approved

#971 [CDS-500] feature: apply accessibility to navbar
  apps/docs/src/pages/components/navbar.mdx
  packages/react-compass/src/navbar/index.ts
  packages/react-compass/src/navbar/navbar-links.styles.ts
  packages/react-compass/src/navbar/navbar-links.tsx
  packages/react-compass/src/navbar/navbar.stories.tsx
  packages/react-compass/src/navbar/navbar.styles.ts
  packages/react-compass/src/navbar/navbar.tsx
Labels: enhancement

#942 [CDS-474] provide accessibility for pagination
  packages/react-compass/src/pagination/pagination.tsx
Labels: approved

#947 [CDS-502] Accessibility for quantity toggle
  packages/react-compass/src/quantity-toggle/utils/useNumberField/index.ts
Labels: approved

#963 [CDS-499] Scan and update accessibility
  packages/react-compass/src/menu-list/menu-list-dropdown-header.tsx
  packages/react-compass/src/menu-list/menu-list.styles.ts
Labels: approved
