Repository comfortdelgro/compass-design, pull requests merged in 2023-08, with the labels that each got.

#948 [CDS-360] Create dropdown-menu component
  apps/docs/src/pages/components/dropdown-menu.mdx
  packages/react-compass/src/dropdown-menu/dropdown-menu-context.ts
  packages/react-compass/src/dropdown-menu/dropdown-menu-item.tsx
  packages/react-compass/src/dropdown-menu/dropdown-menu-menu.tsx
  packages/react-compass/src/dropdown-menu/dropdown-menu-submenu.tsx
  packages/react-compass/src/dropdown-menu/dropdown-menu-toggle.tsx
  packages/react-compass/src/dropdown-menu/dropdown-menu.stories.tsx
  packages/react-compass/src/dropdown-menu/dropdown-menu.styles.ts
  packages/react-compass/src/dropdown-menu/dropdown-menu.tsx
  packages/react-compass/src/dropdown-menu/index.ts
  packages/react-compass/src/index.ts
Labels: approved

#960 [CDS-503] Radio Group - Scan and update accessibility suggested by w3c
  packages/react-compass/src/radio/radio-group.tsx
  packages/react-compass/src/radio/radio.styles.ts
  packages/react-compass/src/radio/radio.tsx
Labels: enhancement

#968 [CDS-494] Checkbox - Scan and update accessibility suggested by w3c
  packages/react-compass/src/checkbox/checkbox.tsx
Labels: enhancement, approved

#981 [CDS-441] Create Chart architecture design document
  packages/react-compass/src/chart/README.md
Labels: documentation

#969 [CDS-497] Link - Scan and update accessibility suggested by w3c
  packages/react-compass/src/link/link.tsx
Labels: enhancement, approved

#934 [CDS-487][Defect][Accessibility] Accordion - User should use tab key to navigate instead of arrow keys
  packages/react-compass/src/accordion/accordion-button.tsx
  packages/react-compass/src/accordion/accordion-title.tsx
  packages/react-compass/src/accordion/accordion.stories.tsx
  packages/react-compass/src/accordion/accordion.styles.ts
  packages/react-compass/src/accordion/accordion.tsx
  packages/react-compass/src/accordion/constants.ts
Labels: enhancement, need-changes

#982 [CDS-441] Create Chart architecture design document
  packages/react-compass/src/chart/README.md
Labels: documentation

#980 [CDS- 485] Product documentation v2
  apps/docs-v2/components/layouts/AppHeader.tsx
  apps/docs-v2/components/products/ProductLogos.tsx
  apps/docs-v2/components/products/ProductServices.tsx
  apps/docs-v2/components/products/ProductsBackground.tsx
  apps/docs-v2/constants/products.tsx
  apps/docs-v2/pages/products/index.tsx
  apps/docs-v2/public/static/images/product-background.png
Labels: documentation

#988 [yagin][hot fix syntax css]
  packages/react-compass/src/searchfield/searchfield.styles.ts
Labels: bug

#1004 [CDS-702] Fix calendar text color
  apps/docs/src/pages/components/calendar.mdx
  apps/docs/src/pages/components/range-calendar.mdx
  packages/react-compass/src/calendar/calendar-cell.style.ts
  packages/react-compass/src/calendar/calendar-header.style.ts
  packages/react-compass/src/calendar/calendar-header.tsx
  packages/react-compass/src/calendar/calendar-month-year-grid.style.ts
  packages/react-compass/src/range-calendar/range-calendar-shortcuts.styles.ts
Labels: bug, documentation, enhancement

#1027 [CDS-756] fix export navbar
  apps/docs-v2/components/layouts/AppHeader.tsx
  packages/react-compass/src/slider/slider.tsx
Labels: bug

#1025 [NGPDCP-2599 & NGPDCP-2600] Drawer component - normal and H5 variants
  packages/react-compass/src/drawer/drawer-expander.tsx
  packages/react-compass/src/drawer/drawer-footer.tsx
  packages/react-compass/src/drawer/drawer-header.tsx
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.styles.ts
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/index.ts
  packages/react-compass/src/drawer/types.ts
  packages/react-compass/src/index.ts
  packages/react-compass/src/utils/hooks/index.ts
  packages/react-compass/src/utils/hooks/useDrag.tsx
Labels: h5

#1030 [NGPDCP-2594] Add new variant sub header component for h5
  packages/react-compass/src/sub-header/index.ts
  packages/react-compass/src/sub-header/sub-header-body.style.ts
  packages/react-compass/src/sub-header/sub-header-body.tsx
  packages/react-compass/src/sub-header/sub-header-description.style.ts
  packages/react-compass/src/sub-header/sub-header-description.tsx
  packages/react-compass/src/sub-header/sub-header-header.style.ts
  packages/react-compass/src/sub-header/sub-header-image.style.ts
  packages/react-compass/src/sub-header/sub-header-image.tsx
  packages/react-compass/src/sub-header/sub-header-title.style.ts
  packages/react-compass/src/sub-header/sub-header-title.tsx
  packages/react-compass/src/sub-header/sub-header.stories.tsx
  packages/react-compass/src/sub-header/sub-header.style.ts
  packages/react-compass/src/sub-header/sub-header.tsx
Labels: h5

#1032 [NGPDCP-2821] H5 checkbox new variant
  packages/react-compass/src/checkbox/checkbox.stories.tsx
  packages/react-compass/src/checkbox/checkbox.styles.ts
  packages/react-compass/src/checkbox/checkbox.tsx
Labels: h5

#1031 [NGPDCP-2596] Update button component for h5
  packages/react-compass/src/button/button.stories.tsx
  packages/react-compass/src/button/button.styles.ts
  packages/react-compass/src/theme/theme.ts
Labels: h5

#1034 [NGPDCP-2823] Add new variant for badge component
  packages/react-compass/src/badge/badge.stories.tsx
  packages/react-compass/src/badge/badge.styles.ts
  packages/react-compass/src/badge/badge.tsx
  packages/react-compass/src/theme/theme.ts
Labels: h5

#1035 [NGPDCP-2822] Toggle H5 variant
  packages/react-compass/src/theme/theme.ts
  packages/react-compass/src/toggle/toggle.stories.tsx
  packages/react-compass/src/toggle/toggle.styles.ts
  packages/react-compass/src/toggle/toggle.tsx
Labels: h5

#1039 fix: Drawer
  packages/react-compass/src/drawer/drawer.styles.ts
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/utils/hooks/useDrag.tsx
Labels: bug, h5

#1040 [CDS-758][Batch 4] Create component pages for all the Interface Components #1037
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/dropdown-menu/DropdownMenuBasic.tsx
  apps/docs-v2/data/components/dropdown-menu/DropdownMenuBasic.tsx.preview
  apps/docs-v2/data/components/dropdown-menu/DropdownMenuSub.tsx
  apps/docs-v2/data/components/dropdown-menu/DropdownMenuSub.tsx.preview
  apps/docs-v2/data/components/dropdown-menu/dropdown-menu.md
  apps/docs-v2/data/components/error/ErrorDefault.tsx
  apps/docs-v2/data/components/error/ErrorDefault.tsx.preview
  apps/docs-v2/data/components/error/ErrorVariant.tsx
  apps/docs-v2/data/components/error/ErrorVariant.tsx.preview
  apps/docs-v2/data/components/error/error.md
  apps/docs-v2/data/components/icon/IconColor.tsx
  apps/docs-v2/data/components/icon/IconColor.tsx.preview
  apps/docs-v2/data/components/icon/IconCountry.tsx
  apps/docs-v2/data/components/icon/IconCountry.tsx.preview
  apps/docs-v2/data/components/icon/IconDuotone.tsx
  apps/docs-v2/data/components/icon/IconDuotone.tsx.preview
  apps/docs-v2/data/components/icon/IconFile.tsx
  apps/docs-v2/data/components/icon/IconFile.tsx.preview
  apps/docs-v2/data/components/icon/IconFilled.tsx
  apps/docs-v2/data/components/icon/IconFilled.tsx.preview
  apps/docs-v2/data/components/icon/IconOther.tsx
  apps/docs-v2/data/components/icon/IconOther.tsx.preview
  apps/docs-v2/data/components/icon/IconOutline.tsx
  apps/docs-v2/data/components/icon/IconOutline.tsx.preview
  apps/docs-v2/data/components/icon/icon.md
  apps/docs-v2/data/components/image-viewer/ImageViewer.tsx
  apps/docs-v2/data/components/image-viewer/ImageViewer.tsx.preview
  apps/docs-v2/data/components/image-viewer/image-viewer.md
  apps/docs-v2/data/components/link/LinkBasic.tsx
  apps/docs-v2/data/components/link/LinkBasic.tsx.preview
  apps/docs-v2/data/components/link/LinkCustom.tsx
  apps/docs-v2/data/components/link/LinkCustom.tsx.preview
  apps/docs-v2/data/components/link/link.md
  apps/docs-v2/data/components/list/ListBasic.tsx
  apps/docs-v2/data/components/list/ListBasic.tsx.preview
  apps/docs-v2/data/components/list/ListCard.tsx
  apps/docs-v2/data/components/list/ListCard.tsx.preview
  apps/docs-v2/data/components/list/ListDragDrop.tsx
  apps/docs-v2/data/components/list/ListDragDrop.tsx.preview
  apps/docs-v2/data/components/list/ListInteractive.tsx
  apps/docs-v2/data/components/list/ListInteractive.tsx.preview
  apps/docs-v2/data/components/list/list.md
  apps/docs-v2/pages/components/dropdown-menu.tsx
  apps/docs-v2/pages/components/error.tsx
  apps/docs-v2/pages/components/icon.tsx
  apps/docs-v2/pages/components/image-viewer.tsx
  apps/docs-v2/pages/components/link.tsx
  apps/docs-v2/pages/components/list.tsx
Labels: documentation

#1037 [CDS-758][Batch 3] Create component pages for all the Interface Components
  apps/docs-v2/components/common/Demo.tsx
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/chip/Chip.tsx
  apps/docs-v2/data/components/chip/Chip.tsx.preview
  apps/docs-v2/data/components/chip/chip.md
  apps/docs-v2/data/components/dashboard-sidecard/DashboardSidecard.tsx
  apps/docs-v2/data/components/dashboard-sidecard/DashboardSidecard.tsx.preview
  apps/docs-v2/data/components/dashboard-sidecard/dashboard-sidecard.md
  apps/docs-v2/data/components/dialog/DialogBasic.tsx
  apps/docs-v2/data/components/dialog/DialogBasic.tsx.preview
  apps/docs-v2/data/components/dialog/DialogNested.tsx
  apps/docs-v2/data/components/dialog/DialogNested.tsx.preview
  apps/docs-v2/data/components/dialog/DialogVariant.tsx
  apps/docs-v2/data/components/dialog/DialogVariant.tsx.preview
  apps/docs-v2/data/components/dialog/dialog.md
  apps/docs-v2/data/components/divider/DividerAlign.tsx
  apps/docs-v2/data/components/divider/DividerAlign.tsx.preview
  apps/docs-v2/data/components/divider/DividerBasic.tsx
  apps/docs-v2/data/components/divider/DividerBasic.tsx.preview
  apps/docs-v2/data/components/divider/divider.md
  apps/docs-v2/data/components/dropdown/DropdownControlled.tsx
  apps/docs-v2/data/components/dropdown/DropdownControlled.tsx.preview
  apps/docs-v2/data/components/dropdown/DropdownHeader.tsx
  apps/docs-v2/data/components/dropdown/DropdownHeader.tsx.preview
  apps/docs-v2/data/components/dropdown/DropdownSection.tsx
  apps/docs-v2/data/components/dropdown/DropdownSection.tsx.preview
  apps/docs-v2/data/components/dropdown/DropdownUncontrolled.tsx
  apps/docs-v2/data/components/dropdown/DropdownUncontrolled.tsx.preview
  apps/docs-v2/data/components/dropdown/dropdown.md
  apps/docs-v2/hooks/useDropdownsForm.ts
  apps/docs-v2/pages/components/chip.tsx
  apps/docs-v2/pages/components/dashboard-sidecard.tsx
  apps/docs-v2/pages/components/dialog.tsx
  apps/docs-v2/pages/components/divider.tsx
  apps/docs-v2/pages/components/dropdown.tsx
  apps/docs/src/pages/components/checkbox.mdx
  packages/react-compass/src/checkbox/checkbox.stories.tsx
Labels: documentation

#1033 [CDS-758][Batch 2] Create component pages for all the Interface Components
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/box/BoxDynamicStyling.tsx
  apps/docs-v2/data/components/box/BoxDynamicStyling.tsx.preview
  apps/docs-v2/data/components/box/BoxElementMapping.tsx
  apps/docs-v2/data/components/box/BoxElementMapping.tsx.preview
  apps/docs-v2/data/components/box/box.md
  apps/docs-v2/data/components/breadcrumbs/BreadcrumbsBasic.tsx
  apps/docs-v2/data/components/breadcrumbs/BreadcrumbsBasic.tsx.preview
  apps/docs-v2/data/components/breadcrumbs/BreadcrumbsCustomDivider.tsx
  apps/docs-v2/data/components/breadcrumbs/BreadcrumbsCustomDivider.tsx.preview
  apps/docs-v2/data/components/breadcrumbs/breadcrumbs.md
  apps/docs-v2/data/components/calendar/Calendar.tsx
  apps/docs-v2/data/components/calendar/Calendar.tsx.preview
  apps/docs-v2/data/components/calendar/calendar.md
  apps/docs-v2/data/components/card/CardSize.tsx
  apps/docs-v2/data/components/card/CardSize.tsx.preview
  apps/docs-v2/data/components/card/CardVariant.tsx
  apps/docs-v2/data/components/card/CardVariant.tsx.preview
  apps/docs-v2/data/components/card/card.md
  apps/docs-v2/data/components/carousel/CarouselMobile.tsx
  apps/docs-v2/data/components/carousel/CarouselMobile.tsx.preview
  apps/docs-v2/data/components/carousel/CarouselPromotion.tsx
  apps/docs-v2/data/components/carousel/CarouselPromotion.tsx.preview
  apps/docs-v2/data/components/carousel/CarouselSlider.tsx
  apps/docs-v2/data/components/carousel/CarouselSlider.tsx.preview
  apps/docs-v2/data/components/carousel/carousel.md
  apps/docs-v2/data/components/carousel/constants.tsx
  apps/docs-v2/data/components/checkbox/CheckboxDefault.tsx
  apps/docs-v2/data/components/checkbox/CheckboxDefault.tsx.preview
  apps/docs-v2/data/components/checkbox/CheckboxUncontrolled.tsx
  apps/docs-v2/data/components/checkbox/CheckboxUncontrolled.tsx.preview
  apps/docs-v2/data/components/checkbox/CheckboxVariant.tsx
  apps/docs-v2/data/components/checkbox/CheckboxVariant.tsx.preview
  apps/docs-v2/data/components/checkbox/checkbox.md
  apps/docs-v2/pages/components/box.tsx
  apps/docs-v2/pages/components/breadcrumbs.tsx
  apps/docs-v2/pages/components/calendar.tsx
  apps/docs-v2/pages/components/card.tsx
  apps/docs-v2/pages/components/carousel.tsx
  apps/docs-v2/pages/components/checkbox.tsx
Labels: documentation

#1029 [CDS-758] Create component pages for all the Interface Components
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/actionbar/ActionBarCenter.tsx
  apps/docs-v2/data/components/actionbar/ActionBarCenter.tsx.preview
  apps/docs-v2/data/components/actionbar/ActionBarDefault.tsx
  apps/docs-v2/data/components/actionbar/ActionBarDefault.tsx.preview
  apps/docs-v2/data/components/actionbar/ActionBarLeft.tsx
  apps/docs-v2/data/components/actionbar/ActionBarLeft.tsx.preview
  apps/docs-v2/data/components/actionbar/ActionBarRight.tsx
  apps/docs-v2/data/components/actionbar/ActionBarRight.tsx.preview
  apps/docs-v2/data/components/actionbar/actionbar.md
  apps/docs-v2/data/components/badges/BadgeBasic.tsx
  apps/docs-v2/data/components/badges/BadgeBasic.tsx.preview
  apps/docs-v2/data/components/badges/BadgeCustom.tsx
  apps/docs-v2/data/components/badges/BadgeCustom.tsx.preview
  apps/docs-v2/data/components/badges/BadgeIcon.tsx
  apps/docs-v2/data/components/badges/BadgeIcon.tsx.preview
  apps/docs-v2/data/components/badges/badges.md
  apps/docs-v2/data/components/banner/BannerBasic.tsx
  apps/docs-v2/data/components/banner/BannerBasic.tsx.preview
  apps/docs-v2/data/components/banner/BannerCustom.tsx
  apps/docs-v2/data/components/banner/BannerCustom.tsx.preview
  apps/docs-v2/data/components/banner/BannerSizing.tsx
  apps/docs-v2/data/components/banner/BannerSizing.tsx.preview
  apps/docs-v2/data/components/banner/banner.md
  apps/docs-v2/pages/components/actionbar.tsx
  apps/docs-v2/pages/components/badges.tsx
  apps/docs-v2/pages/components/banner.tsx
Labels: documentation

#1041 [NGPDC-2597] confirm PU point component
  packages/react-compass/src/confirm-pickup/confirm-pickup.stories.tsx
  packages/react-compass/src/confirm-pickup/confirm-pickup.styles.ts
  packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
  packages/react-compass/src/confirm-pickup/index.ts
  packages/react-compass/src/index.ts
Labels: h5

#1036 [NGPDCP-2595] PUDO component
  packages/react-compass/src/index.ts
  packages/react-compass/src/pudo/index.ts
  packages/react-compass/src/pudo/pudo-item.tsx
  packages/react-compass/src/pudo/pudo.config.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
  packages/react-compass/src/pudo/pudo.styles.ts
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
Labels: h5

#1042 [CDS-776] Radio wrong style
  packages/react-compass/src/radio/radio.styles.ts
Labels: bug

#1043 Fix build h5
  packages/react-compass/src/confirm-pickup/confirm-pickup.tsx
  packages/react-compass/src/toggle/toggle.tsx
Labels: bug

#1049 Drawer - add ability to disable default accessibility behavior: autofocus and close
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.styles.ts
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/index.ts
  packages/react-compass/src/drawer/types.ts
  packages/react-compass/src/index.ts
Labels: h5

#1051 [CDS-768] Update docs search
  apps/docs-v2/components/common/Demo.tsx
  apps/docs-v2/components/common/DemoToolbar.tsx
  apps/docs-v2/components/home/Introduction/index.tsx
  apps/docs-v2/components/home/Introduction/item.tsx
  apps/docs-v2/components/home/ReactCompass/ShowcaseContainer.tsx
  apps/docs-v2/components/home/ReactCompass/index.tsx
  apps/docs-v2/components/layouts/AppSearch.tsx
  apps/docs-v2/components/layouts/DocsAppSideNav.tsx
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/pages/foundation/overview.tsx
  apps/docs-v2/pages/global.css
  apps/docs-v2/types/common.ts
  apps/docs-v2/utils/index.ts
  apps/docs-v2/utils/search.ts
Labels: approved

#1061 Drawer: logic & prop name changes
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/types.ts
Labels: h5

#1052 [CDS-758][Batch 5] Create component pages for all the Interface Components
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/menu-list/MenuList.tsx
  apps/docs-v2/data/components/menu-list/MenuList.tsx.preview
  apps/docs-v2/data/components/menu-list/menu-list.md
  apps/docs-v2/data/components/modal/ModalDefault.tsx
  apps/docs-v2/data/components/modal/ModalDefault.tsx.preview
  apps/docs-v2/data/components/modal/ModalNested.tsx
  apps/docs-v2/data/components/modal/ModalNested.tsx.preview
  apps/docs-v2/data/components/modal/ModalVariant.tsx
  apps/docs-v2/data/components/modal/ModalVariant.tsx.preview
  apps/docs-v2/data/components/modal/modal.md
  apps/docs-v2/data/components/navbar/Navbar.tsx
  apps/docs-v2/data/components/navbar/Navbar.tsx.preview
  apps/docs-v2/data/components/navbar/navbar.md
  apps/docs-v2/data/components/otp-input/OTPInput.tsx
  apps/docs-v2/data/components/otp-input/OTPInput.tsx.preview
  apps/docs-v2/data/components/otp-input/otp-input.md
  apps/docs-v2/data/components/page-header/PageHeader.tsx
  apps/docs-v2/data/components/page-header/PageHeader.tsx.preview
  apps/docs-v2/data/components/page-header/page-header.md
  apps/docs-v2/data/components/popover/Popover.tsx
  apps/docs-v2/data/components/popover/Popover.tsx.preview
  apps/docs-v2/data/components/popover/popover.md
  apps/docs-v2/data/components/portal/PortalLayout.tsx
  apps/docs-v2/data/components/portal/PortalLayout.tsx.preview
  apps/docs-v2/data/components/portal/portal.md
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleControlled.tsx
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleControlled.tsx.preview
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleUnControlled.tsx
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleUnControlled.tsx.preview
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleUnit.tsx
  apps/docs-v2/data/components/quantity-toggle/QuantityToggleUnit.tsx.preview
  apps/docs-v2/data/components/quantity-toggle/quantity-toggle.md
  apps/docs-v2/pages/components/menu-list.tsx
  apps/docs-v2/pages/components/modal.tsx
  apps/docs-v2/pages/components/navbar.tsx
  apps/docs-v2/pages/components/otp-input.tsx
  apps/docs-v2/pages/components/page-header.tsx
  apps/docs-v2/pages/components/popover.tsx
  apps/docs-v2/pages/components/portal.tsx
  apps/docs-v2/pages/components/quantity-toggle.tsx
Labels: documentation

#1063 [CDS-804][Docs] Drawer component
  apps/docs-v2/constants/routes.ts
  apps/docs-v2/data/components/drawer/Drawer.tsx
  apps/docs-v2/data/components/drawer/Drawer.tsx.preview
  apps/docs-v2/data/components/drawer/DrawerCustomize.tsx
  apps/docs-v2/data/components/drawer/DrawerCustomize.tsx.preview
  apps/docs-v2/data/components/drawer/DrawerH5.tsx
  apps/docs-v2/data/components/drawer/DrawerH5.tsx.preview
  apps/docs-v2/data/components/drawer/DrawerMode.tsx
  apps/docs-v2/data/components/drawer/DrawerMode.tsx.preview
  apps/docs-v2/data/components/drawer/DrawerPosition.tsx
  apps/docs-v2/data/components/drawer/DrawerPosition.tsx.preview
  apps/docs-v2/data/components/drawer/drawer.md
  apps/docs-v2/pages/components/drawer.tsx
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.styles.ts
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/types.ts
Labels: documentation, h5

#1069 [NGPDCP-2923] Implement H5 variant for Textarea component
  apps/docs-v2/data/components/textarea/TextareaH5.tsx
  apps/docs-v2/data/components/textarea/TextareaH5.tsx.preview
  apps/docs-v2/data/components/textarea/textarea.md
  packages/react-compass/src/textarea/textarea.stories.tsx
  packages/react-compass/src/textarea/textarea.styles.ts
  packages/react-compass/src/textarea/textarea.tsx
Labels: h5
