Repository comfortdelgro/compass-design, pull requests merged in 2023-11, with the labels that each got.

#1318 [CDS-925] PUDO component - use static CSS
  packages/static/src/index.ts
  packages/static/src/pudo/index.ts
  packages/static/src/pudo/pudo-item.tsx
  packages/static/src/pudo/pudo.config.tsx
  packages/static/src/pudo/pudo.stories.tsx
  packages/static/src/pudo/pudo.tsx
  packages/static/src/pudo/pudo.types.ts
  packages/static/src/pudo/styles/pudo-stories.module.css
  packages/static/src/pudo/styles/pudo.module.css
Labels: documentation, enhancement

#1319 [CDS-902] Implementation of Progress Bar for static
  packages/static/src/index.ts
  packages/static/src/progress-bar/index.ts
  packages/static/src/progress-bar/progress-bar.stories.tsx
  packages/static/src/progress-bar/progress-bar.tsx
  packages/static/src/progress-bar/styles/progress-bar.module.css
  packages/static/src/utils/objectToCss/object-to-css.ts
Labels: enhancement

#1331 [CDS-951] convert Tooltip component to static css
  packages/static/src/index.ts
  packages/static/src/tooltip/index.ts
  packages/static/src/tooltip/styles/tooltip.module.css
  packages/static/src/tooltip/tooltip-context.tsx
  packages/static/src/tooltip/tooltip-trigger.tsx
  packages/static/src/tooltip/tooltip.stories.tsx
  packages/static/src/tooltip/tooltip.tsx
Labels: enhancement

#1332 [CDS-961] convert SpeedDial component to static css
  apps/docs/data/components/speed-dial/SpeedDialServer.tsx
  apps/docs/data/components/speed-dial/speed-dial.md
  packages/static/src/index.ts
  packages/static/src/speed-dial/index.ts
  packages/static/src/speed-dial/speed-dial-action.tsx
  packages/static/src/speed-dial/speed-dial-trigger.tsx
  packages/static/src/speed-dial/speed-dial.stories.tsx
  packages/static/src/speed-dial/speed-dial.tsx
  packages/static/src/speed-dial/styles/speed-dial.module.css
Labels: enhancement

#1333 [CDS-950] convert Toggle component to static css
  apps/docs/data/components/toggle/ToggleServer.tsx
  apps/docs/data/components/toggle/toggle.md
  packages/static/src/index.ts
  packages/static/src/toggle/index.ts
  packages/static/src/toggle/styles/toggle.module.css
  packages/static/src/toggle/toggle.stories.tsx
  packages/static/src/toggle/toggle.tsx
Labels: enhancement

#1358 [CDS-981] PUDO features update & improvement
  apps/docs/data/components/pudo/PudoAlignIcon.tsx
  apps/docs/data/components/pudo/PudoAlignIcon.tsx.preview
  apps/docs/data/components/pudo/PudoCompact.tsx
  apps/docs/data/components/pudo/PudoCustomType.tsx
  apps/docs/data/components/pudo/PudoCustomType.tsx.preview
  apps/docs/data/components/pudo/PudoLabelView.tsx
  apps/docs/data/components/pudo/PudoLabelView.tsx.preview
  apps/docs/data/components/pudo/pudo.md
  packages/react-compass/src/pudo/pudo-item.tsx
  packages/react-compass/src/pudo/pudo.config.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
  packages/react-compass/src/pudo/pudo.styles.ts
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
  packages/static/package.json
  packages/static/src/pudo/pudo-item.tsx
  packages/static/src/pudo/pudo.config.tsx
  packages/static/src/pudo/pudo.stories.tsx
  packages/static/src/pudo/pudo.tsx
  packages/static/src/pudo/pudo.types.ts
  packages/static/src/pudo/styles/pudo-stories.module.css
  packages/static/src/pudo/styles/pudo.module.css
  pnpm-lock.yaml
Labels: documentation, enhancement

#1363 [CDS-983] Checkbox mismatch selected style
  packages/static/src/checkbox/styles/checkbox.module.css
Labels: approved

#1360 [CDS-977] font not apply in static
  packages/static/.storybook/preview-head.html
  packages/static/src/scripts/generate-theme.js
  packages/static/src/scripts/theme.config.js
  packages/static/src/theme/fonts.module.css
  packages/static/src/theme/fonts/poppins/Poppins-Black.woff2
  packages/static/src/theme/fonts/poppins/Poppins-BlackItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Bold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-BoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraBold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraBoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraLight.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraLightItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Italic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Light.woff2
  packages/static/src/theme/fonts/poppins/Poppins-LightItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Medium.woff2
  packages/static/src/theme/fonts/poppins/Poppins-MediumItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Regular.woff2
  packages/static/src/theme/fonts/poppins/Poppins-SemiBold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-SemiBoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Thin.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ThinItalic.woff2
  packages/static/src/utils/objectToCss/object-to-css.ts
Labels: bug, enhancement

#1356 [CDS-968] Implementation of Video player for static
  apps/docs/data/components/video-player/VideoPlayerServer.tsx
  apps/docs/data/components/video-player/video-player.md
  packages/static/src/index.ts
  packages/static/src/video-player/icon.tsx
  packages/static/src/video-player/index.ts
  packages/static/src/video-player/styles/video-player.module.css
  packages/static/src/video-player/styles/volume-slider.module.css
  packages/static/src/video-player/video-player.stories.tsx
  packages/static/src/video-player/video-player.tsx
  packages/static/src/video-player/volume-slider/volume-slider.tsx
Labels: enhancement

#1357 [CDS-980] Remove internationalized/number
  packages/static/package.json
  packages/static/src/quantity-toggle/utils/useNumberField/useNumberFormatter.ts
  packages/static/src/quantity-toggle/utils/useNumberFieldState/index.ts
  pnpm-lock.yaml
Labels: approved

#1369 docs-fix: Drawer & PUDO - incorrect default values
  apps/docs/data/components/drawer/drawer.md
  apps/docs/data/components/pudo/PudoCompact.tsx
  apps/docs/data/components/pudo/PudoManipulation.tsx
Labels: bug, documentation

#1375 [CDS-988] add utils component styles
  packages/static/src/utils/components.module.css
Labels: enhancement

#1374 [CDS-987] change static for snack bar component
  packages/static/src/index.ts
  packages/static/src/snackbar/hooks/useSnackbar.ts
  packages/static/src/snackbar/index.tsx
  packages/static/src/snackbar/service/index.ts
  packages/static/src/snackbar/service/snackbar-container.tsx
  packages/static/src/snackbar/service/snackbar-context.tsx
  packages/static/src/snackbar/service/snackbar-item.tsx
  packages/static/src/snackbar/service/snackbar-reducer.ts
  packages/static/src/snackbar/service/snackbar-service.ts
  packages/static/src/snackbar/service/types.ts
  packages/static/src/snackbar/snackbar-prefix-icon.tsx
  packages/static/src/snackbar/snackbar-suffix-icon.tsx
  packages/static/src/snackbar/snackbar-text.tsx
  packages/static/src/snackbar/snackbar.stories.tsx
  packages/static/src/snackbar/snackbar.tsx
  packages/static/src/snackbar/styles/snackbar-item.module.css
  packages/static/src/snackbar/styles/snackbar.module.css
Labels: enhancement

#1372 [CDS-986] change static for error component
  apps/docs/data/components/error/ErrorServer.tsx
  apps/docs/data/components/error/error.md
  packages/static/src/error/error-action.tsx
  packages/static/src/error/error-description.tsx
  packages/static/src/error/error-icon.tsx
  packages/static/src/error/error-image.tsx
  packages/static/src/error/error-title.tsx
  packages/static/src/error/error.stories.tsx
  packages/static/src/error/error.tsx
  packages/static/src/error/index.ts
  packages/static/src/error/styles/error.module.css
  packages/static/src/index.ts
Labels: enhancement

#1370 Feature/should trigger onchange start date
  apps/docs/data/components/date-range-picker/date-range-picker.md
  packages/react-compass/src/calendar/hooks/useCalendarCell.ts
  packages/react-compass/src/calendar/hooks/useRangeCalendarState.ts
  packages/react-compass/src/calendar/types/calendar.types.ts
  packages/react-compass/src/calendar/types/range-calendar.types.ts
  packages/react-compass/src/date-range-picker/date-range-picker.stories.tsx
  packages/react-compass/src/date-range-picker/date-range-picker.tsx
  packages/react-compass/src/range-calendar/range-calendar.tsx
  packages/static/src/calendar/hooks/useCalendarCell.ts
  packages/static/src/calendar/hooks/useRangeCalendarState.ts
  packages/static/src/calendar/types/calendar.types.ts
  packages/static/src/calendar/types/range-calendar.types.ts
  packages/static/src/date-range-picker/DateRangePicker.stories.tsx
  packages/static/src/date-range-picker/date-range-picker.tsx
  packages/static/src/range-calendar/range-calendar.tsx
Labels: enhancement

#1381 [CDS-990] add index export member
  packages/static/src/index.ts
  packages/static/src/utils/index.ts
Labels: enhancement

#1385 [CDS-988] add utils components
  packages/static/src/index.ts
  packages/static/src/utils/components/Column.tsx
  packages/static/src/utils/components/Flexbox.tsx
  packages/static/src/utils/components/Row.tsx
  packages/static/src/utils/components/components.module.css
  packages/static/src/utils/components/index.ts
  packages/static/src/utils/index.ts
Labels: enhancement

#1397 [CDS-1003] remove local font and add pagination comp
  apps/docs/data/components/pagination/PaginationBasic.tsx
  apps/docs/data/components/pagination/PaginationControlled.tsx
  apps/docs/data/components/pagination/PaginationItemsCounting.tsx
  apps/docs/data/components/pagination/PaginationServer.tsx
  apps/docs/data/components/pagination/pagination.md
  apps/docs/data/components/popover/Popover.tsx
  apps/docs/data/getting-started/installation/installation.md
  apps/docs/package.json
  apps/docs/pages/_app.tsx
  apps/docs/pages/_document.tsx
  apps/docs/pages/global.css
  packages/react-compass/src/theme/theme.ts
  packages/static/.storybook/preview-head.html
  packages/static/src/preflight/styles/preflight.module.css
  packages/static/src/scripts/generate-theme.js
  packages/static/src/scripts/theme.config.js
  packages/static/src/theme/fonts.module.css
  packages/static/src/theme/fonts/poppins/Poppins-Black.woff2
  packages/static/src/theme/fonts/poppins/Poppins-BlackItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Bold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-BoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraBold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraBoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraLight.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ExtraLightItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Italic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Light.woff2
  packages/static/src/theme/fonts/poppins/Poppins-LightItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Medium.woff2
  packages/static/src/theme/fonts/poppins/Poppins-MediumItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Regular.woff2
  packages/static/src/theme/fonts/poppins/Poppins-SemiBold.woff2
  packages/static/src/theme/fonts/poppins/Poppins-SemiBoldItalic.woff2
  packages/static/src/theme/fonts/poppins/Poppins-Thin.woff2
  packages/static/src/theme/fonts/poppins/Poppins-ThinItalic.woff2
  packages/static/src/theme/theme.module.css
  packages/static/src/theme/theme.ts
Labels: bug, documentation

#1405 Enhancement: Tooltip portal render
  packages/react-compass/src/tooltip/tooltip-trigger.tsx
  packages/static/src/tooltip/tooltip-trigger.tsx
Labels: enhancement

#1399 [Hotfix] Pagination stale closure
  packages/react-compass/src/pagination/pagination.hooks.ts
  packages/react-compass/src/pagination/pagination.tsx
  packages/static/src/pagination/pagination.hooks.ts
  packages/static/src/pagination/pagination.tsx
Labels: bug

#1407 Fix/cds 812 sidebar padding
  packages/react-compass/src/sidebar/sidebar.styles.ts
  packages/static/src/sidebar/styles/sidebar.module.css
Labels: bug

#1406 Fix/cds 750 slider outline
  packages/react-compass/src/slider/slider.styles.ts
  packages/static/src/slider/styles/slider.module.css
Labels: bug

#1410 Drawer - Add ability to programmatically collapse the drawer
  apps/docs/data/components/drawer/DrawerCollapseRef.tsx
  apps/docs/data/components/drawer/DrawerCollapseRef.tsx.preview
  apps/docs/data/components/drawer/DrawerExpose.tsx
  apps/docs/data/components/drawer/DrawerExpose.tsx.preview
  apps/docs/data/components/drawer/DrawerMode.tsx
  apps/docs/data/components/drawer/drawer.md
  packages/react-compass/src/drawer/drawer-pick-child.ts
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.tsx
  packages/react-compass/src/drawer/index.ts
  packages/react-compass/src/drawer/types.ts
  packages/react-compass/src/index.ts
  packages/static/src/drawer/Drawer.stories.tsx
  packages/static/src/drawer/drawer-pick-child.ts
  packages/static/src/drawer/drawer.tsx
  packages/static/src/drawer/index.ts
  packages/static/src/drawer/styles/drawer-stories.module.css
  packages/static/src/drawer/types.ts
  packages/static/src/index.ts
Labels: documentation, enhancement

#1408 fix: image viewer center when release mouse
  packages/react-compass/src/image-viewer/ViewerCanvas.tsx
  packages/static/src/image-viewer/ViewerCanvas.tsx
Labels: enhancement

#1422 PUDO: remove item `label` type & improve UI
  apps/docs/data/components/pudo/Pudo.tsx
  apps/docs/data/components/pudo/PudoCompact.tsx
  apps/docs/data/components/pudo/PudoCustomType.tsx
  apps/docs/data/components/pudo/pudo.md
  apps/docs/data/components/pudo/styles/CompactExampleContainer.module.css
  apps/docs/data/components/pudo/styles/PrewviewCode.module.css
  apps/docs/data/components/pudo/styles/pudo-docs.module.css
  packages/react-compass/src/pudo/pudo-item.tsx
  packages/react-compass/src/pudo/pudo.config.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
  packages/react-compass/src/pudo/pudo.styles.ts
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
  packages/static/src/pudo/pudo-item.tsx
  packages/static/src/pudo/pudo.config.tsx
  packages/static/src/pudo/pudo.stories.tsx
  packages/static/src/pudo/pudo.tsx
  packages/static/src/pudo/pudo.types.ts
  packages/static/src/pudo/styles/pudo.module.css
Labels: documentation

#1423 PUDO: CSS styles - complexity reduction
  packages/react-compass/src/pudo/pudo-item.tsx
  packages/react-compass/src/pudo/pudo.stories.tsx
  packages/react-compass/src/pudo/pudo.styles.ts
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
  packages/static/src/pudo/pudo-item.tsx
  packages/static/src/pudo/pudo.stories.tsx
  packages/static/src/pudo/pudo.tsx
  packages/static/src/pudo/pudo.types.ts
  packages/static/src/pudo/styles/pudo.module.css
Labels: documentation
