Repository comfortdelgro/compass-design, pull requests merged in 2024-01, with the labels that each got.

#1467 [CDS-1029] Update docs (adding more props) for the new docs
  apps/docs/data/components/button/LinkButton.tsx
  apps/docs/data/components/button/LinkButton.tsx.preview
  apps/docs/data/components/button/button.md
Labels: documentation

#1464 PUDO - add item swap event listener
  apps/docs/data/components/drawer/drawer.md
  apps/docs/data/components/pudo/pudo.md
  packages/react-compass/src/pudo/pudo.tsx
  packages/react-compass/src/pudo/pudo.types.ts
  packages/static/src/pudo/pudo.tsx
  packages/static/src/pudo/pudo.types.ts
Labels: enhancement

#1451 [CDS-1026]Pagination rows per pages not change
  packages/react-compass/src/pagination/pagination.tsx
  packages/static/src/pagination/pagination.tsx
Labels: bug

#1450 [CDS-1007]Link button appearance deforms when using with list tag
  packages/static/src/button/button.tsx
  packages/static/src/button/styles/button.module.css
Labels: bug

#1447 [CDS-835] Table V2 - The resizing function is not working in mobile mode
  apps/docs/data/components/table/table.md
  packages/react-compass/src/table-v2/table-v2-progress.styles.ts
  packages/react-compass/src/table-v2/table-v2-resizer.styles.ts
  packages/static/src/box/box.tsx
  packages/static/src/index.ts
  packages/static/src/table-v2/index.tsx
  packages/static/src/table-v2/table-v2.tsx
  packages/static/src/table/index.tsx
  packages/static/src/table/styles/table-progress.module.css
  packages/static/src/table/styles/table-resizer.module.css
  packages/static/src/table/table-column-header-filter.tsx
  packages/static/src/table/table-column-header.tsx
  packages/static/src/table/table-resizer.tsx
  packages/static/src/table/table.tsx
Labels: bug

#1491 fix: Drawer - `preventFocus` correction
  apps/docs/data/components/drawer/DrawerCustomize.tsx
  packages/react-compass/src/drawer/drawer.stories.tsx
  packages/react-compass/src/drawer/drawer.tsx
  packages/static/src/drawer/Drawer.stories.tsx
  packages/static/src/drawer/drawer.tsx
Labels: bug
